### ISSUE TITLE
Bug: sort-object-types - don't fail when multiple interfaces have the same value

### ISSUE THREAD

**Issue by dylang** [azat-io/eslint-plugin-perfectionist#10]
### Describe the bug

This is a wild one. 

Easier to show with a screenshot:
<img width="1081" alt="Screenshot 2023-06-09 at 5 19 14 PM" src="https://github.com/azat-io/eslint-plugin-perfectionist/assets/51505/4005518d-8a71-42c9-9a47-3226c5fdda24">

### Code example

Code is from the answer on https://stackoverflow.com/questions/52760509/typescript-returntype-of-overloaded-function (I'm thanking my past-self for remembering to include the link to where I got this code!)

```ts
type OverloadedReturnType<T> = T extends {
    (...args: any[]): infer R;
    (...args: any[]): infer R;
    (...args: any[]): infer R;
    (...args: any[]): infer R;
}
    ? R
    : T extends { (...args: any[]): infer R; (...args: any[]): infer R; (...args: any[]): infer R }
    ? R
    : T extends { (...args: any[]): infer R; (...args: any[]): infer R }
    ? R
    : T extends (...args: any[]) => infer R
    ? R
    : any;
```

### ESLint version

v8.41.0

### ESLint Plugin Perfectionist version

v1.1.0

### Additional comments

Hopefully rare, I was able to just use `eslint-disable` to avoid the issue.

### Validations

- [X] Read the [docs](https://eslint-plugin-perfectionist.azat.io).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Fixed in 623ac67bd0a1bf54aa24cf0ac6eff971653104e9

Released in [v1.1.1](https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v1.1.1)
