### ISSUE TITLE
Bug: [perfectionist/sort-objects] unexpected behavior on Windows

### ISSUE THREAD

**Issue by gustaveWPM** [azat-io/eslint-plugin-perfectionist#105]
### Describe the bug

The `perfectionist/sort-objects` rule is glitched on Windows.

### Code example

Failing workflow : https://github.com/Tirraa/dashboard_rtm/actions/runs/7926565974

Failing workflow related commit : https://github.com/Tirraa/dashboard_rtm/commit/d2f313191a09cebf0b73a671941528084e95942c

---

Working workflow : https://github.com/Tirraa/dashboard_rtm/actions/runs/7926583540

Working workflow related commit : https://github.com/Tirraa/dashboard_rtm/commit/1123819379709d2a36fa4f98eea0cd7d5371253e

### ESLint version

v8.47.0 (also tested with v8.56.0)

### ESLint Plugin Perfectionist version

v2.5.0

### Validations

- [X] Read the [docs](https://eslint-plugin-perfectionist.azat.io).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Curious. An unusual problem. Thanks, I'll look into your issue.

**Comment by gustaveWPM** [comment]
> Curious. An unusual problem. Thanks, I'll look into your issue.

Yes, I find it very strange too.
I've triggered this bug a few times and hesitated to create this issue...

**Comment by azat-io** [comment]
It seems that the log retention period has expired.

I tested your problem, but was unable to reproduce it. If the problem persists, I will reopen your issue.
