### ISSUE TITLE
Feature: Ignore Bun modules

### ISSUE THREAD

**Issue by vpzomtrrfrt** [azat-io/eslint-plugin-perfectionist#109]
### What rule do you want to change?

sort-imports

### Describe the problem

Since 37bca14, this module considers `ws` a builtin module, but this is not the case in Node. This should probably be behind a configuration option

### Code example

```
import { IncomingMessage } from "http";

import winston from "winston";
import WebSocket from "ws";
```

### Validations

- [X] Read the [docs](https://eslint-plugin-perfectionist.azat.io).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Thank you for your issue!

This feature was implemented in c8b2fa4b8a7fcbd1155d592720fc86511700cdd4 and released in [v3.0.0](https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v3.0.0).

If you'd like, you can support the release with a retweet:
https://x.com/azat_io_en/status/1815367279191761054
