### ISSUE TITLE
Feature: Add support for Vue order in components rules

### ISSUE THREAD

**Issue by alexkiro** [azat-io/eslint-plugin-perfectionist#112]
### What rule do you want to change?

sort-objects

### Describe the problem

Currently the [sort-objects](https://eslint-plugin-perfectionist.azat.io/rules/sort-objects) rule is incompatible with the [order-in-components](https://eslint.vuejs.org/rules/order-in-components).

It would be nice if these two could be used together somehow. As far as I can tell there is no way of making them compatible as is. 

### Code example

```vue
<template>
  <foo-bar></foo-bar>
</template>

<script lang="ts">
import FooBar from "@/components/FooBar.vue";

export default {
  name: "HomeView",
  components: { FooBar },
};
</script>
```

`perfectionist/sort-objects` would like to put `components` first, but `vue/order-in-components` would like to put `name` first since it has it's custom hardcoded order. 

### Additional comments

I tried using `ignore-pattern` but it doesn't seem to work. Presumably since there is no variable identifier available, so presumably it just skips checking for null names such as this. 

### Validations

- [X] Read the [docs](https://eslint-plugin-perfectionist.azat.io).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by Tragio** [comment]
Currently I'm using something like this:

```
    'perfectionist/sort-vue-attributes': [
      'error',
      {
        // Based on: https://vuejs.org/style-guide/rules-recommended.html#element-attribute-order
        'custom-groups': {
          /* eslint-disable perfectionist/sort-objects */
          DEFINITION: 'is',
          LIST_RENDERING: 'v-for',
          CONDITIONALS: 'v-*(else-if|if|else|show|cloak)',
          RENDER_MODIFIERS: 'v-*(pre|once)',
          GLOBAL: 'id',
          UNIQUE: '*(ref|key)',
          SLOT: '*(v-slot|slot)',
          TWO_WAY_BINDING: 'v-model',
          EVENTS: '*(v-on|@*)',
          CONTENT: 'v-*(html|text)',
          /* eslint-enable perfectionist/sort-objects */
        },
        groups: [
          'DEFINITION',
          'LIST_RENDERING',
          'CONDITIONALS',
          'RENDER_MODIFIERS',
          'GLOBAL',
          'UNIQUE',
          'SLOT',
          'TWO_WAY_BINDING',
          'unknown',
          'EVENTS',
          'CONTENT',
        ],
        type: 'natural',
      },
    ],
  ```

**Comment by BenJackGill** [comment]
> Currently I'm using something like this:
> 
> ```
>     'perfectionist/sort-vue-attributes': [
>       'error',
>       {
>         // Based on: https://vuejs.org/style-guide/rules-recommended.html#element-attribute-order
>         'custom-groups': {
>           /* eslint-disable perfectionist/sort-objects */
>           DEFINITION: 'is',
>           LIST_RENDERING: 'v-for',
>           CONDITIONALS: 'v-*(else-if|if|else|show|cloak)',
>           RENDER_MODIFIERS: 'v-*(pre|once)',
>           GLOBAL: 'id',
>           UNIQUE: '*(ref|key)',
>           SLOT: '*(v-slot|slot)',
>           TWO_WAY_BINDING: 'v-model',
>           EVENTS: '*(v-on|@*)',
>           CONTENT: 'v-*(html|text)',
>           /* eslint-enable perfectionist/sort-objects */
>         },
>         groups: [
>           'DEFINITION',
>           'LIST_RENDERING',
>           'CONDITIONALS',
>           'RENDER_MODIFIERS',
>           'GLOBAL',
>           'UNIQUE',
>           'SLOT',
>           'TWO_WAY_BINDING',
>           'unknown',
>           'EVENTS',
>           'CONTENT',
>         ],
>         type: 'natural',
>       },
>     ],
> ```

Thank you for this, just what I was looking for.

Although I feel it would be better to have this as the default setting, or at least an easy option to turn on via the `groups` option like so:

```JavaScript
  "rules": {
    "perfectionist/sort-vue-attributes": [
      "error",
      {
        "groups": ["vue-order"]
      }
    ]
  }
```

**Comment by BenJackGill** [comment]
I was having issues with the other groups. It seems [the style guide docs](https://vuejs.org/style-guide/rules-recommended.html#element-attribute-order) are not as correct as the [eslint-plugin-vue docs](https://eslint.vuejs.org/rules/attributes-order.html).

It's almost exactly the same as before but I combined `["UNIQUE", "SLOT"]` and added `OTHER_DIRECTIVES`. And it differs from the eslint-plugin-vue docs by using `unknown` in place of `OTHER_ATTR` which I assume is correct.

```
    "perfectionist/sort-vue-attributes": [
      "error",
      {
        // Based on: https://vuejs.org/style-guide/rules-recommended.html#element-attribute-order
        "custom-groups": {
          /* eslint-disable perfectionist/sort-objects */
          DEFINITION: "is",
          LIST_RENDERING: "v-for",
          CONDITIONALS: "v-*(if|else-if|else|show|cloak)",
          RENDER_MODIFIERS: "v-*(pre|once)",
          GLOBAL: "id",
          UNIQUE: "*(ref|key)",
          SLOT: "*(v-slot|slot)",
          TWO_WAY_BINDING: "v-model",
          OTHER_DIRECTIVES: "v-*",
          EVENTS: "*(v-on|@*)",
          CONTENT: "v-*(html|text)",
          /* eslint-enable perfectionist/sort-objects */
        },
        groups: [
          "DEFINITION",
          "LIST_RENDERING",
          "CONDITIONALS",
          "RENDER_MODIFIERS",
          "GLOBAL",
          ["UNIQUE", "SLOT"],
          "TWO_WAY_BINDING",
          "OTHER_DIRECTIVES",
          "unknown",
          "EVENTS",
          "CONTENT",
        ],
        type: "natural",
      },
    ],
```

**Comment by azat-io** [comment]
Thank you for your issue!

I think this problem can be easily solved by creating custom groups.
