### ISSUE TITLE
Bug: (sort-exports) does not work for 'export *'

### ISSUE THREAD

**Issue by mqwerty** [azat-io/eslint-plugin-perfectionist#119]
### Describe the bug

sort-exports rule does not work for 'export *'

```js
// .eslintrc.cjs
'perfectionist/sort-exports': [
  'error',
  {
    'type': 'alphabetical',
    'order': 'asc',
  },
],
```

### Code example

```js
export * from './b'
export * from './a' // <- There must be a error here
```

### ESLint version

8.57.0

### ESLint Plugin Perfectionist version

2.6.0

### Validations

- [X] Read the [docs](https://eslint-plugin-perfectionist.azat.io).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by snevolin** [comment]
Just stumbled upon the problem, would really like a fix

**Comment by azat-io** [comment]
This is done for security reasons.

Example: 

```
// a.js
export function func {
  return 1
}
```

```
// b.js
export function func {
  return 2
}
```

Depending on the priority, we will have different function values.

We intentionally do not sort exports with an `*` because there may be conflicts.

**Comment by snevolin** [comment]
Actually, this problem doesn’t exist in TypeScript because these conflicts are immediately visible. Maybe we could consider implementing sorting just for ts files?

**Comment by azat-io** [comment]
Could you please demonstrate what the conflicts look like in the TS files?

**Comment by snevolin** [comment]
`// a.ts
export function func () {
  return 1
}
`
`// b.ts
export function func () {
  return 2
}`

And if you put exports in index.ts like this
`export * from './b'
export * from './a'`

You''ll get a TS error:
`Module './b' has already exported a member named 'func'. Consider explicitly re-exporting to resolve the ambiguity.ts(2308)`
