### ISSUE TITLE
Bug: (sort-object): Cannot read properties of undefined (reading 'getTokensBefore')

### ISSUE THREAD

**Issue by bab2683** [azat-io/eslint-plugin-perfectionist#121]
### Describe the bug

Getting that error when running the linter

### Code example

```
const something = {
  b: false,
  a: true,
};
```

### ESLint version

8.36

### ESLint Plugin Perfectionist version

2.7.0

### Additional comments

Apple M3 Pro
macOS Sonoma 14.3

### Validations

- [X] Read the [docs](https://eslint-plugin-perfectionist.azat.io).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Looks like a problem with the typescript-eslint version.
What package manager are you using?

**Comment by bab2683** [comment]
We're using `yarn@1.22.211` and  `@typescript-eslint/utils@6.8.0`

**Comment by bab2683** [comment]
BTW, I just tried upgrading `@typescript-eslint/eslint-plugin`, `@typescript-eslint/parser` and `@typescript-eslint/utils` to latest non breaking version `6.21.0` and the issue is still reproducible

**Comment by azat-io** [comment]
Do you have the ability to create a small repository to reproduce the problem?

**Comment by bab2683** [comment]
Hi, sorry for the delay, you can reproduce it here:
https://github.com/bab2683/perfectionist-121

**Comment by azat-io** [comment]
<img width="541" alt="image" src="https://github.com/azat-io/eslint-plugin-perfectionist/assets/5698350/0a20acfd-c454-4d9a-a698-1b1741617a90">

Looks like the removing parser fix this issue.

**Comment by bab2683** [comment]
To use typescript however, is necessary due to the differences in AST format. at least that's what they say right in the first line https://typescript-eslint.io/packages/parser/. I thought this eslint plugin was compatible with the whole `@typescript-eslint` suite due to the `sort-interfaces` rule and also because it's listed as dependency.

We use the parser in the overwrites because we have both js and ts files in the project
