### ISSUE TITLE
Bug: sort-imports sorts individually in custom-groups array

### ISSUE THREAD

**Issue by GasparAdragna** [azat-io/eslint-plugin-perfectionist#136]
### Describe the bug

Im having a problem with the auto-sorting of the imports.

I have a custom group like so:

` 
"components": ["@components/**", "./components/**"],
`

But the alphabetical sorting is doing it individually, once for @components and then for ./components

### Code example

<img width="1083" alt="image" src="https://github.com/azat-io/eslint-plugin-perfectionist/assets/38141596/54edeeee-840d-4400-80ad-e2e874c03866">

This is the rest of the .eslintrc.json:

```javascript
{
  "extends": [
    "next",
    "prettier",
    "next/core-web-vitals",
    "plugin:storybook/recommended",
    "plugin:perfectionist/recommended-alphabetical"
  ],
  "plugins": ["@typescript-eslint", "perfectionist"],
  "parser": "@typescript-eslint/parser",
  "rules": {
    "react/jsx-uses-react": 0,
    "react/react-in-jsx-scope": 0,
    "@typescript-eslint/no-unused-vars": "error",
    "@typescript-eslint/no-explicit-any": "error",
    "quotes": ["error", "double"],
    "no-restricted-imports": [
      "error",
      {
        "paths": [
          {
            "name": "@nextui-org/react",
            "importNames": ["Link"],
            "message": "Please use Link from @/navigation if href is local or ExternalLink if you wish to navigate outside the project"
          }
        ]
      }
    ],
    "perfectionist/sort-imports": [
      "error",
      {
        "type": "alphabetical",
        "order": "asc",
        "ignore-case": true,
        "newlines-between": "always",
        "groups": [
          "react",
          ["builtin", "external"],
          "assets",
          "config",
          "constants",
          "components",
          "graphql",
          "hooks",
          "icons",
          "stores",
          "styles",
          "utils",
          "types",
          "all",
          ["parent", "sibling", "index"]
        ],
        "custom-groups": {
          "value": {
            "react": ["react", "react-*"],
            "assets": "@assets/**",
            "config": "@config/**",
            "constants": "@constants/**",
            "components": ["@components/**", "./components/**"],
            "graphql": "@graphql/**",
            "hooks": "@hooks/**",
            "icons": "@icons/**",
            "stores": "@stores/**",
            "styles": "@styles/**",
            "utils": "@utils/**",
            "types": "types/**",
            "all": "@/**"
          }
        }
      }
    ]
  },
  "root": true,
  "ignorePatterns": ["newrelic.js"]
}

``` 

### ESLint version

8.54

### ESLint Plugin Perfectionist version

2.9.0

### Validations

- [X] Read the [docs](https://eslint-plugin-perfectionist.azat.io).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
This behavior is expected. The plugin compares the values and sorts them alphabetically.

```js
['@', '.'].sort() // ['.', '@']
```

In your case, you can only separate the component imports into two separate groups.

**Comment by GasparAdragna** [comment]
There is no way of ordering them as a group? I dont get why i can group them but not order them, seems counterintuitive .

I would like to group all of my components into a single group

**Comment by azat-io** [comment]
There is currently no such opportunity. If we had such a feature, what might the configuration look like?

Perhaps you have some ideas how it should be configured.

**Comment by GasparAdragna** [comment]
Thanks for the fast replies, i only have one more question.

Why if its sorting correctly (first '.' and then '@'), its showing them in the oposite way?

When i save the file i can see that it "jumps" from the correct order to the one i show in the picture. I don’t  know if something is overriding the configuration but i cannot find anything that might interfere .

https://github.com/azat-io/eslint-plugin-perfectionist/assets/38141596/c9589ca3-96de-469f-af27-b9f9aec15d3d

**Comment by azat-io** [comment]
Imports that start with a `.` alphabetically go earlier than those that start with a `@`.

Perhaps we should in the future add the ability to create subgroups that would sort values within groups, given the order defined within them.
