### ISSUE TITLE
Feature: implement ignore-pattern based on word before, not object name

### ISSUE THREAD

**Issue by rtatarinov** [azat-io/eslint-plugin-perfectionist#137]
### What rule do you want to change?

ignore-inline-pattern

### Describe the problem

I have the following problem. When I use for example `effector` library (store managment) I have a strict order in the specific cases. For example:
```js
import { sample } from "effector";

sample({
      clock: event,
      source: $store,
      filter: isNotNil,
      fn: (sourceData => sourceData.id,
      target: effectFx,
});
```

This is a right ordering in the `sample` operator from effector. But it conflicts with `asc` ordering from `sort-objects`
The library allows to `ignore-pattern` for any object with specific name/file name. But I don't use name at all. So, the following implementation doesn't work: 
```js
"perfectionist/sort-objects": [
       "error",
        {
             "order": "asc",
             "type": "natural",
             "ignore-pattern": ["sample(*"]
        }
  ],
  ```
  
  **Proposal**
  Implement inline code cheching by regex to check symbol by symbol string and exclude anything matches the specific pattern

### Code example

```js
"perfectionist/sort-objects": [
            "error",
            {
                "order": "asc",
                "type": "natural",
                "ignore-inline-pattern": ["sample(*"]
            }
],
```

### Validations

- [X] Read the [docs](https://eslint-plugin-perfectionist.azat.io).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Thank you for your issue!

I think your idea will be useful for many users.

This feature was implemented in 471de409ae3e181ff344522d1ad45b0b2d7d2192 and released in [v3.0.0](https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v3.0.0).

If you'd like, you can support the release with a retweet:
https://x.com/azat_io_en/status/1815367279191761054
