### ISSUE TITLE
Feature: Providing Disabling Rules that Conflict

### ISSUE THREAD

**Issue by ofk** [azat-io/eslint-plugin-perfectionist#141]
### Describe the rule

The eslint-plugin-perfectionist may conflict with existing rules. For instance, [eslint-plugin-perfectionist/sort-imports](https://eslint-plugin-perfectionist.azat.io/rules/sort-imports) requires disabling the built-in `sort-imports` and `import/order` rules. I believe it would be more convenient if plugins offer such rules to disable.

### Code example

```js
import perfectionistNatural from 'eslint-plugin-perfectionist/configs/recommended-natural'
import perfectionistTurnoff from 'eslint-plugin-perfectionist/configs/recommended-turnoff'

export default [
  perfectionistNatural,
  perfectionistTurnoff, // { rules: { 'sort-imports': 0, 'import/order': 0, … } }
]
```

### Additional comments

Providing disabling of conflicting rules like this is already done by [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier).

### Validations

- [X] Read the [docs](https://eslint-plugin-perfectionist.azat.io).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
I think this is not a very obvious behaviour for a config.

For example, if a user wants to import a config but disable our rule in favour of a conflicting one.

We don't plan to do that.
