### ISSUE TITLE
Feature: sort-imports sort order by group order in line-length

### ISSUE THREAD

**Issue by matheusdsilva01** [azat-io/eslint-plugin-perfectionist#142]
### What rule do you want to change?

sort-imports

### Describe the problem

The possibility of sorting by group order.
I believe it would be something like: "sort-order-groups": true

`sort-order-groups` rule with first `create` after `get`:
```json
"perfectionist/sort-imports": [
      "warn",
      {
        "type": "line-length",
        "order": "desc",
        "groups": [
          ["create", "get"],
          ["builtin", "external"]
        ],
        "custom-groups": {
          "value": {
            "get": "../utils/get/**/*",
            "create": "../utils/create/**/*"
          }
        },
        "newlines-between": "always",
        "sort-groups": true
      }
    ]
```

### Code example

without `sort-order-groups` rule, sort this:
```js
import { createEslintRule } from '../utils/create'
import { createEslint } from '../utils/create'
import { getLinesBetween } from '../utils/get'
import { getGroupNumber } from '../utils/get'
import { createRule } from '../utils/create'
import { getNodeRange } from '../utils/get'
import { getGroup } from '../utils/get'
```
with `"sort-order-groups": true` rule:
```js
import { createEslintRule } from '../utils/create'
import { createEslint } from '../utils/create'
import { createRule } from '../utils/create'
import { getLinesBetween } from '../utils/get'
import { getGroupNumber } from '../utils/get'
import { getNodeRange } from '../utils/get'
import { getGroup } from '../utils/get'
```

### Additional comments

I used Google Translate for this issue, sorry if there are some grammatical errors 😄

### Validations

- [X] Read the [docs](https://eslint-plugin-perfectionist.azat.io).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Thank you for your issue!

Thank you for your idea. I don't think it will be in demand at this time. And at the moment we have no plans to implement this feature.
