### ISSUE TITLE
Bug: no type definition for eslint flat config

### ISSUE THREAD

**Issue by TheElegantCoding** [azat-io/eslint-plugin-perfectionist#144]
### Describe the bug

when importing eslint plugin perfectionist i get this
![image](https://github.com/azat-io/eslint-plugin-perfectionist/assets/70770072/7a8340a9-f3b0-42f8-8034-ede32b18bb34)

### Code example

```ts
import pluginPerfectionist from 'eslint-plugin-perfectionist';

const perfectionist =
{
  name: 'perfectionist',
  plugins:
  {
    perfectionist: pluginPerfectionist
  },
  rules:
  {
    ...perfectionistGeneralRule
  }
};

export { perfectionist };
```

### ESLint version

8.57.0

### ESLint Plugin Perfectionist version

2.10.0

### Validations

- [X] Read the [docs](https://eslint-plugin-perfectionist.azat.io).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Duplicate #139
