### ISSUE TITLE
Bug: dependency mismatch with eslint-plugin-svelte

### ISSUE THREAD

**Issue by Arikael** [azat-io/eslint-plugin-perfectionist#156]
### Describe the bug

While https://github.com/azat-io/eslint-plugin-perfectionist/commit/861a381 resolved the earlier issue `eslint-plugin-svelte` updated their dependency of `svelte-eslint-parser` to `^0.38.0` while this project uses `^0.37.0`.

Meaning despite the new release those two plugins still can't be used together in their newest version

### Code example

no code

### ESLint version

8.57.0

### ESLint Plugin Perfectionist version

2.11.0

### Validations

- [X] Read the [docs](https://eslint-plugin-perfectionist.azat.io).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by slingshotvfx** [comment]
Seems like updates are happening quickly, I'm still having this problem with v3.0.0 and `eslint-plugin-svelte@2.43.0`

```shell
npm ERR! Found: svelte-eslint-parser@0.41.0
npm ERR! node_modules/svelte-eslint-parser
npm ERR!   svelte-eslint-parser@"^0.41.0" from eslint-plugin-svelte@2.43.0
npm ERR!   node_modules/eslint-plugin-svelte
npm ERR!     dev eslint-plugin-svelte@"^2.40.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! dev eslint-plugin-perfectionist@"*" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: svelte-eslint-parser@0.40.0
npm ERR! node_modules/svelte-eslint-parser
npm ERR!   peerOptional svelte-eslint-parser@"^0.40.0" from eslint-plugin-perfectionist@3.0.0
npm ERR!   node_modules/eslint-plugin-perfectionist
npm ERR!     dev eslint-plugin-perfectionist@"*" from the root project
```

**Comment by philsherry** [comment]
Had to uninstall it while things calm down. 

```log
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: eslint-plugin-perfectionist@3.9.1
npm error Found: svelte-eslint-parser@0.43.0
npm error node_modules/svelte-eslint-parser
npm error   svelte-eslint-parser@"^0.43.0" from eslint-plugin-svelte@2.46.0
npm error   node_modules/eslint-plugin-svelte
npm error     dev eslint-plugin-svelte@"^2.45.1" from the root project
npm error
npm error Could not resolve dependency:
npm error peerOptional svelte-eslint-parser@"^0.41.1" from eslint-plugin-perfectionist@3.9.1
npm error node_modules/eslint-plugin-perfectionist
npm error   dev eslint-plugin-perfectionist@"^3.9.1" from the root project
npm error
npm error Conflicting peer dependency: svelte-eslint-parser@0.41.1
npm error node_modules/svelte-eslint-parser
npm error   peerOptional svelte-eslint-parser@"^0.41.1" from eslint-plugin-perfectionist@3.9.1
npm error   node_modules/eslint-plugin-perfectionist
npm error     dev eslint-plugin-perfectionist@"^3.9.1" from the root project
```

**Comment by azat-io** [comment]
@philsherry The problem is mismatching versions of svelte-eslint-parser.

However, I strongly recommend not using the `perfectionist/sort-svelte-attributes` rule. This rule is deprecated.
Use `svelte/sort-attributes` instead:
https://sveltejs.github.io/eslint-plugin-svelte/rules/sort-attributes/
