### ISSUE TITLE
Bug: Issue with subpath imports

### ISSUE THREAD

**Issue by jude98** [azat-io/eslint-plugin-perfectionist#161]
### Describe the bug

While using the perfectionist plugin for ESLint to sort imports in a TypeScript project, there is a circular sorting error when sorting imports between certain custom groups. Specifically, the error occurs when sorting @assets and #hooks imports.

### Description
The ESLint perfectionist/sort-imports rule is configured to sort imports alphabetically and within defined groups. However, a circular sorting error arises with the following custom groups:

	•	subpath-import: #hooks/** (I have added subpath imports in package.json)
	•	assets: @assets/**
	
When the @assets imports are placed above the #hooks imports, ESLint complains:
```
Expected "#hooks/useWalletConnection" to come before "@assets/icons".
```

When #hooks imports are placed above @assets imports, ESLint complains:
```
`@assets/icons` import should occur before import of `#hooks/useWalletConnection`.
```

This creates a conflict, causing a circular sorting error.

### Code example

Below is the relevant part of the ESLint configuration: (.eslintrc)

```json
"perfectionist/sort-imports": [
  "error",
  {
    "type": "alphabetical",
    "order": "asc",
    "groups": [
      "type",
      "react",
      ["builtin", "external"],
      "subpath-import",
      "assets",
      ["parent-type", "sibling-type", "index-type"],
      ["parent", "sibling", "index"],
      "side-effect",
      "style",
      "object",
      "unknown"
    ],
    "custom-groups": {
      "value": {
        "react": ["react", "react-dom/client"],
        "subpath-import": ["#hooks/**"],
        "assets": ["@assets/**", "**/*.svg", "**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif"],
      },
      "type": {
        "react": "react"
      }
    },
    "newlines-between": "always",
    "internal-pattern": [
      "@routes/**",
      "@components/**",
      "@screens/**",
      "@hooks/**",
      "@theme/**",
      "@constants/**",
      "@utils/**"
    ]
  }
]
```

### ESLint version

v8.57.0

### ESLint Plugin Perfectionist version

v2.10.0

### Validations

- [X] Read the [docs](https://eslint-plugin-perfectionist.azat.io).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Hi!
I have no way to reproduce your problem. Could you please create a repository to reproduce it?

**Comment by azat-io** [comment]
Closed due to lack of activity.
