### ISSUE TITLE
Feature: Support folding regions

### ISSUE THREAD

**Issue by adrianpufu** [azat-io/eslint-plugin-perfectionist#166]
### Describe the rule

I'm not really sure if this should be considered a bug or an enhancement but we sometimes use folding regions to create code groups based on the logic/feature they describe. This does not seem to be supported by the sorting and the regions are mixed around after running the autofix. 
I would expect them to be treated as sorting sections (items sorted only within the section), and maybe sorted themselves by name?

### Code example

Before autofix:
```ts
export class ExampleComponent {
  // #region Table
  protected updateTable() {}

  protected onSortChanged() {}

  protected onPaginationChanged() {}

  protected onChangeColumns() {}
  // #endregion

  // #region Form
  protected onValueChanged() {}

  protected setFormValue() {}

  protected disableForm() {}

  protected clearForm() {}
  // #endregion
}
```
After running autofix:
```ts
export class ExampleComponent {
  protected clearForm() {}

  protected disableForm() {}

  protected onChangeColumns() {}

  protected onPaginationChanged() {}
  // #endregion

  protected onSortChanged() {}

  // #region Form
  protected onValueChanged() {}

  protected setFormValue() {}

  // #region Table
  protected updateTable() {}
  // #endregion
}
```

### Validations

- [X] Read the [docs](https://eslint-plugin-perfectionist.azat.io).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Thank you for your issue!

Partition by comment option was added in da01c853288ce1438ee0e55c99c98d1aa28948f0 and released in [v3.0.0](https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v3.0.0).

If you'd like, you can support the release with a retweet:
https://x.com/azat_io_en/status/1815367279191761054
