### ISSUE TITLE
Feature: Create "@types/eslint-plugin-perfectionist" package

### ISSUE THREAD

**Issue by GlebVarVar** [azat-io/eslint-plugin-perfectionist#170]
### Describe the rule

When I am using eslint.config.js, code editor submit a warning about module declaration.

### Code example

Could not find a declaration file for module 'eslint-plugin-perfectionist'. '/home/anega/itmo/design-system/app/node_modules/eslint-plugin-perfectionist/dist/index.mjs' implicitly has an 'any' type.
  Try `npm i --save-dev @types/eslint-plugin-perfectionist` if it exists or add a new declaration (.d.ts) file containing `declare module 'eslint-plugin-perfectionist';

### Validations

- [X] Read the [docs](https://eslint-plugin-perfectionist.azat.io).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Hi, this feature is already done and will appear in our upcoming release.

**Comment by azat-io** [comment]
Thank you for your issue!

Types were added in 2b63ab558f431a33fbdfb103c3279ec34011d135 and released in [v3.0.0](https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v3.0.0).

If you'd like, you can support the release with a retweet:
https://x.com/azat_io_en/status/1815367279191761054
