### ISSUE TITLE
Feature: Add `optionality-order` option to `sort-object-types` rule

### ISSUE THREAD

**Issue by stormwarning** [azat-io/eslint-plugin-perfectionist#172]
### What rule do you want to change?

sort-object-types

### Describe the problem

`interface` types can be configured to group required fields before optional fields; it would be great to have this option for `type` types as well.

### Code example

With this option, between the `sort-object-types` and `sort-interfaces` rules we'd have an autofixable version of this configuration of `@typescript-eslint/member-ordering`

```js
'@typescript-eslint/member-ordering': [
	'warn',
	{
		interfaces: {
			order: 'natural-case-insensitive',
			optionalityOrder: 'required-first',
		},
		typeLiterals: {
			order: 'natural-case-insensitive',
			optionalityOrder: 'required-first',
		},
	},
],
```

### Validations

- [X] Read the [docs](https://eslint-plugin-perfectionist.azat.io).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Thank you for your issue!

This feature was implemented in 96cfcd8be3dee5870a14de1736e76af7632cc8b0 and released in [v3.0.0](https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v3.0.0).

If you'd like, you can support the release with a retweet:
https://x.com/azat_io_en/status/1815367279191761054
