### ISSUE TITLE
Deprecate rules for sorting Vue, Svelte and Astro attributes

### ISSUE THREAD

**Issue by azat-io** [azat-io/eslint-plugin-perfectionist#175]
Three rules were added in version 2.0.0:

- `sort-vue-attributes`
- `sort-svelte-attributes`
- `sort-astro-atttributes`

At the moment I'm thinking about giving them up. There are several reasons for this:

1. These rules use non-standard JavaScript or TypeScript syntax. For this reason, we have to use other parsers along with them:
    - [vue-eslint-parser](https://github.com/vuejs/vue-eslint-parser)
    - [svelte-eslint-parser](https://github.com/sveltejs/svelte-eslint-parser)
    - [astro-eslint-parser](https://github.com/ota-meshi/astro-eslint-parser)
    
    That's a hard thing to maintain.
    
2. These rules extend beyond the plugin’s core ideology. The primary goal is to support sorting various elements that are part of the JavaScript, TypeScript, or JSX/TSX language standards.
    
    Supporting third-party libraries and frameworks could make the plugin unwieldy and complicated for users.
    
    Currently, we only plan to support standard pieces.
    
3. There are already similar ESLint rules:
    - [vue/attributes-order](https://eslint.vuejs.org/rules/attributes-order.html)
    - [svelte/sort-attributes](https://sveltejs.github.io/eslint-plugin-svelte/rules/sort-attributes/)
    
    These rules could serve as adequate replacements.
    

I have a suggestion, move the missing functionality to ESLint plugins Vue, Svelte and Astro and maintain it there. First of all, it is the ability to sort attributes not only alphabetically, but also by line length.

The Astro plugin currently lacks this rule, so it could be transferred in its entirety.

I was interested to hear @ota-meshi opinion as the author of these plugins.

I would also like to hear the opinions of other users of the plugin.

**Comment by idmytro** [comment]
[vue/attributes-order](https://eslint.vuejs.org/rules/attributes-order.html) is better than nothing.
Your rule looks like more powerful, but it doesn't work well.

**Comment by azat-io** [comment]
@idmytro We need to have the same rule in eslint-plugin-astro to make it all deprecated

**Comment by azat-io** [comment]
Before deprecating the rules, we plan to improve the rules in the corresponding ESLint plugins. Also we plan to add features to the `vue/attributes-order` rule.

**Comment by azat-io** [comment]
Added in 46790ea.
Releases in [v3.9.0](https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v3.9.0).

**Comment by fvilers** [comment]
I'm a Svelte developer and I love `perfectionist` a lot as it matches my taste on code organisation. The `sort-svelte-attributes` suits my needs. I understand why it is deprecated and why it should be removed from this package. But I can't find how to configure `svelte/sort-attributes` to behave the same way than the perfectionist one does. Could you provide some guidance or a migration guide to match the same rule behavior?

**Comment by azat-io** [comment]
@fvilers Can you tell me what settings you have used previously? And what is missing in `svelte/sort-attributes`?

**Comment by azat-io** [comment]
@ota-meshi Can we create an issue in https://github.com/sveltejs/eslint-plugin-svelte ?

**Comment by ambethia** [comment]
Is it not possible to sort imports with this in svelte anymore either now?

**Comment by mikededo** [comment]
Hey @fvilers, I was also using the `svelte/sort-attributes` rule. I ended up extracting the rule into it's own in a single plugin, in case you are interested. Note that all credits go to @azat-io and those who contributed to create the rule, as I simply re-used and adapted the rule. Check the [repo here](https://github.com/mikededo/eslint-plugin-svelte-sort-attributes)!

**Comment by fvilers** [comment]
Thanks @mikededo, in  the meantime I fallback to `svelte/sort-attributes` but I'll definitively look into your repo.
