### ISSUE TITLE
Typescript error 'Property 'configs' does not exist on type....

### ISSUE THREAD

**Issue by Sparticuz** [azat-io/eslint-plugin-perfectionist#177]
### Describe the bug

```
Property 'configs' does not exist on type 'typeof import("/home/kyle/dev/eslint-config/node_modules/eslint-plugin-perfectionist/dist/index")'.ts(2339)
```

### Code example

```ts
import perfectionist from "eslint-plugin-perfectionist";
import tseslint from "typescript-eslint";

export default tseslint.config(
  perfectionist.configs["recommended-natural"],
);
```

### ESLint version

8.57

### ESLint Plugin Perfectionist version

3

### Additional comments

I'm wondering if the error is because of `tseslint.config()` helper function. `// @ts-expect-error` ignores it, and it does seem to work.

![image](https://github.com/user-attachments/assets/1b174343-0b4e-458f-a6e5-80bad7b8becb)

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by Sparticuz** [comment]
Actually, maybe it's not working.

**Comment by azat-io** [comment]
Thank you for your issue!

I'll check it today.

**Comment by scagood** [comment]
I noticed a similar thing, I ended up just patching the types like this:

```ts
declare module 'eslint-plugin-perfectionist' {
    import type { ESLint } from 'eslint';
    export default {} as WithRequired<ESLint.Plugin, 'environments'>;
}
```

It looks to be all confused about whether the default export is a default export:
<img width="550" alt="image" src="https://github.com/user-attachments/assets/c30c935b-c561-4847-8d03-085fa0529c58">
My editor thinks `default` is a property 😓

**Comment by Pewtro** [comment]
For what it is worth, I don't have this issue when using 3.0.0 - my IDE is detecting the appropriate types automatically.

**Comment by azat-io** [comment]
The problem seems to have gone away after upgrading to typescript-eslint v8 in 05b65027f7c6ff8354db98f883359e2f0e724a86. I tried testing version [v3.1.0](https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v3.1.0) in my IDE.

**Comment by JoshuaKGoldberg** [comment]
This still exists for me with `typescript-eslint@8.0.0` and `eslint-plugin-perfectionist@3.1.2`.

Reproduction repository: https://github.com/JoshuaKGoldberg/repros/tree/repro-eslint-plugin-perfectionist-default-export-types

@azat-io would you be up for reopening this please? 🙏
