### ISSUE TITLE
Feature: Sort React Hook Dependency Arrays

### ISSUE THREAD

**Issue by stevensacks** [azat-io/eslint-plugin-perfectionist#178]
### Describe the rule

First off, amazing plugin. I just discovered it today. I've been using separate sorting plugins and now I can just use perfectionist!

React Hook dependency array order has no effect on functionality. In keeping with sorting everywhere else, I wrote my own ESLint plugin to sort them.

https://github.com/stevensacks/eslint-plugin-sort-react-dependency-arrays

It seems like this functionality would be a natural addition to your great library. Perhaps you'd consider adding it? Thanks!

### Code example

Before:
```ts
useEffect(() => {
  // ... some code
}, [t, isSubmitting, success, error]);
```
After:
```ts
useEffect(() => {
  // ... some code
}, [error, isSubmitting, success, t]);
```

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Thank you for your issue!

We don't plan to support things specific to any tools or frameworks.

Nevertheless, I find your idea a good one. I recommend you to create a similar issue in the eslint-plugin-react repository.

**Comment by stevensacks** [comment]
I’m not sure I understand what you mean.

You have rules for [Vue](https://perfectionist.dev/rules/sort-vue-attributes) and [Svelte](https://perfectionist.dev/rules/sort-svelte-attributes) and [Astro](https://perfectionist.dev/rules/sort-astro-attributes) and [React/JSX](https://perfectionist.dev/rules/sort-jsx-props)

**Comment by azat-io** [comment]
JSX support is built-in to ESLint.

We plan to deprecate support for Vue, Astro and Svelte in favour of their respective plugins.

Read more:
https://github.com/azat-io/eslint-plugin-perfectionist/issues/175

**Comment by stevensacks** [comment]
Ah, ok. I understand. Thanks for taking the time and for making this plugin. I included it in a series of articles I wrote about ESLint rules.

https://react-japan.dev/en/blog/eslint-sorting

**Comment by azat-io** [comment]
@stevensacks Wow, that looks cool. Thank you so much for your support!

**Comment by gajus** [comment]
For React, you can use https://github.com/gajus/eslint-plugin-canonical?tab=readme-ov-file#sort-react-dependencies

(I am deprecating other sorting rules for this plugin)

**Comment by stevensacks** [comment]
> For React, you can use https://github.com/gajus/eslint-plugin-canonical?tab=readme-ov-file#sort-react-dependencies
> 
> (I am deprecating other sorting rules for this plugin)

@gajus If you look at the OP, you can see that I wrote a plugin that does this, and was asking for it to be integrated.

**Comment by stevensacks** [comment]
Thanks. I’m going to use a few of your rules, as well!
