### ISSUE TITLE
Bug: sort-imports rule breaks on dynamic require

### ISSUE THREAD

**Issue by brokenmass** [azat-io/eslint-plugin-perfectionist#184]
### Describe the bug

in plugin version 3.0 (likely because of https://github.com/azat-io/eslint-plugin-perfectionist/commit/bc16243), sort-imports rule breaks if the code contains a dynamic require or, i guess, anything that is not a string literal.
```ts
const a = require('a'); // ok
const path = './something.js';
require(path); // breaks
require(path.join(baseDir, './package.json')); // breaks
require(`./something.js`); // breaks
```

error is `TypeError: cannot read properties of undefined (reading toString) at registerNode (sort-imports/js:335:40)`

can be fixed by ignoring non literal requires 
```ts
VariableDeclaration: node => {
        if (
          node.declarations[0].init &&
          node.declarations[0].init.type === 'CallExpression' &&
          node.declarations[0].init.callee.type === 'Identifier' &&
          node.declarations[0].init.callee.name === 'require' &&
          node.declarations[0].init.arguments[0]?.type === 'Literal' 
        ) {
          registerNode(node)
        }
      },
```
but you might want to change it to something more robust (or to actually sort dynamic requires somehow)

### ESLint version

v9.7.0

### ESLint Plugin Perfectionist version

v3.0.0

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Thank you for your issue!

This problem was fixed in 68632dfc74d1254325ea509c22975372f65f062e and released in [v3.1.0](https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v3.1.0).
