### ISSUE TITLE
Bug: toSorted is not a function

### ISSUE THREAD

**Issue by Leomaradan** [azat-io/eslint-plugin-perfectionist#185]
### Describe the bug

The new rule sort-switch-case seems to have break our project. 

The error message is : `TypeError: nodeGroups.map(...).toSorted is not a function`, located in `node_modules/eslint-plugin-perfectionist/dist/rules/sort-switch-case.mjs:150:20`

### Code example

(nothing in particular)

### ESLint version

9.8.0

### ESLint Plugin Perfectionist version

3.0.0

### Additional comments

According to the documentation, the toSorted method is supported for Node 20.x (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/toSorted)

Our environment use Node 18.19.1

If I switch to Node 20.16.0, there is no error, but we cannot switch to this version for some other dependencies.

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Thank you for your issue!

This problem was fixed in bff6575dca2006fceaf36680bef392f615808890 and released in [[v3.1.0](https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v3.1.0)](https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v3.1.0).
