### ISSUE TITLE
Bug: `perfectionist/sort-switch-case` breaks code with consecutive ENUM case statements

### ISSUE THREAD

**Issue by hugoAlt** [azat-io/eslint-plugin-perfectionist#187]
### Describe the bug

`perfectionist/sort-switch-case` rule incorrectly reformats code using `switch` on consecutive ENUM cases into code with different behavior.

### Code example

```typescript
enum ApiRestMethodEnum {
  GET = 'GET',
  POST = 'POST',
}

let restMethod: string;
switch (restMethod) {
  case ApiRestMethodEnum.POST:
  case ApiRestMethodEnum.GET:
    console.log("Print me")
    break;
}
```

gets formatted into the following code:
``` typescript
enum ApiRestMethodEnum {
  GET = 'GET',
  POST = 'POST',
}

let restMethod: string;
switch (restMethod) {
  case ApiRestMethodEnum.GET:
    console.log("Print me")
    break;
  case ApiRestMethodEnum.POST:
}
```

### ESLint version

8.57.0

### ESLint Plugin Perfectionist version

3.0.0

### Additional comments

Possibly related to #180: 

![image](https://github.com/user-attachments/assets/18afbfea-8c62-4ad4-aa81-3b6127970c69)

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Thank you for your issue!

This problem was solved in d07f5f77cdb54b8eec32269695ab04f31d85a5f7 and released in [v3.1.0](https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v3.1.0).
