### ISSUE TITLE
Bug: `perfectionist/sort-switch-case` breaks eslint on consecutive string case statements

### ISSUE THREAD

**Issue by hugoAlt** [azat-io/eslint-plugin-perfectionist#188]
### Describe the bug

`perfectionist/sort-switch-case` rule breaks eslint when using `switch` on consecutive string cases.

### Code example

```typescript
let restMethod;
switch (restMethod) {
  case "POST":
  case "GET":
    console.log("Print me")
    break;
}
```
The code above breaks eslint with the following error:
```
TypeError: Cannot read properties of null (reading 'makeNext')
```

The code below does not break eslint but reformats incorrectly into code with different behavior.
```typescript
let restMethod
switch (restMethod) {
  case 1:
  case "POST":
  case "GET":
    console.log("Print me")
    break;
}
```

The code below breaks eslint with the same error however:
```typescript
let restMethod
switch (restMethod) {
  case "POST":
  case 1:
  case "GET":
    console.log("Print me")
    break;
}
```

### ESLint version

8.57.0

### ESLint Plugin Perfectionist version

3.0.0

### Additional comments

Possibly related to #187.

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Thank you for your issue!

This problem was solved in d07f5f77cdb54b8eec32269695ab04f31d85a5f7 and released in [v3.1.0](https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v3.1.0).
