### ISSUE TITLE
Feature: Add `readonly` properties to perfectionist/sort-classes

### ISSUE THREAD

**Issue by christopher-buss** [azat-io/eslint-plugin-perfectionist#193]
### Describe the rule

I would like the option to group by readonly properties.

I used to use the following extension to organize variables, but I found this to be overall an issue as I couldn't run it through ESLint, therefore it couldn't be run in CI, or other team members wouldn't always know to format.
https://github.com/aljazsim/vs-code-typescript-class-organizer/blob/master/src/member-type.ts

I'd basically like to try get as close to this ordering as possible through ESLint, and readonly properties are one of the main constraints here.

### Code example

Currently the ordering is like this:
```ts
private readonly runway = 5;
private sParticipants = new Array<Player>();
private readonly voted = new Set<Player>();
```

But I'd like them to be able to be grouped as such:
```ts
private readonly runway = 5;
private readonly voted = new Set<Player>();

private sParticipants = new Array<PlayerEntity>();
```

### Additional comments

I realise I may be able to achieve this with custom groups already, but I believe readonly would make sense as a builtin. The original ESLint [rule](https://typescript-eslint.io/rules/member-ordering/#member-types-granular-form) (which had no autofix) supported readonly properties.

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Added in baa701d494baa8d01f977a650080fb52c61dbc46.
Released in [v3.2.0](https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v3.2.0).
