### ISSUE TITLE
Feature: Add `groupKind` option to `perfectionist/sort-classes`

### ISSUE THREAD

**Issue by OlivierZal** [azat-io/eslint-plugin-perfectionist#197]
### What rule do you want to change?

`perfectionist/sort-classes`

### Describe the problem

Like for `perfectionist/sort-interfaces`, a `groupKind: 'optional-first' | 'required-first' | 'mixed' = 'mixed'` option would be useful and allow what the `optionalityOrder?: 'optional-first' | 'required-first'` option does for the frozen [member-ordering](https://typescript-eslint.io/rules/member-ordering/) rule.

### Code example

The proposed option exists [here](https://github.com/azat-io/eslint-plugin-perfectionist/blob/main/rules/sort-interfaces.ts#L26) for another rule (`perfectionist/sort-interfaces`).

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by OlivierZal** [comment]
@hugop95, FYI

**Comment by hugop95** [comment]
Would it be better to have this setting at the top level (like in `perfectionist/sort-interfaces`), or a more granular level through a `modifier`? (`optional` vs `required`)? 

```json
groups": [
    "optional-property",
    "required-property",
    "optional-method",
    "required-method",
```

**Comment by OlivierZal** [comment]
I don't know if there can be optional groups other than properties: I don't think that optional methods exist, do they?

However, even if different groups could be optional, I don't see any use case where a developer would like optional first for the ones and required first for the others: rather seems a developer choice of consistency for his/her whole code.

That's why I think that `perfectionist/sort-interfaces`'s `groupKind` covers the main use cases (and then would avoid complex code and configuration for too few usage).

**Comment by hugop95** [comment]
One possible implementation without having to touch the node sorting method itself (which is common to all rules) is to add the `optional` modifier to `property`, and have the `optional-first` flag add before each user group that same group, but with the `optional` modifier as well.

Example to illustrate:

```json
"groupKind": "optional-first",
"groups": [
              "index-signature",
              "public-static-property",
              "property"
]
```

would internally change the groups to

```json
"groups": [
              "index-signature",
              "public-static-optional-property",
              "public-static-property",
              "optional-property",
              "property"
]
```

The `optional` groups would be added below for `required-first`.

**Comment by OlivierZal** [comment]
In my opinion it seems cleaner to handle it in the `for (let nodes of formattedNodes)` loop, similarly to https://github.com/azat-io/eslint-plugin-perfectionist/blob/c30c8eeedfbf714130006209b0f3096a92aca010/rules/sort-object-types.ts#L216

**Comment by hugop95** [comment]
Definitely looks easier to handle here indeed!

**Comment by hugop95** [comment]
Feature ready, PR will be created when https://github.com/azat-io/eslint-plugin-perfectionist/pull/210 is merged.

**Comment by OlivierZal** [comment]
@hugop95, @azat-io, what do you think about making `groupKind` a list by adding the possibility another option (and more in the future as needed): `decorated-by-element-name` (default) | `decorated-by-decorator-name`?

**Comment by OlivierZal** [comment]
Ok for consistency, that's important. 

The use case I add in mind is someone who wants to gather the `@Infer`, etc. But indeed it's not a major use case.

**Comment by OlivierZal** [comment]
@azat-io, if you prefer @hugop95 and since optional exists only for properties, maybe the best would be to give up with `groupKind` and simply add an `-optional-` modifier, wouldn't be?

**Comment by hugop95** [comment]
@azat-io I have made a PR implementing @OlivierZal 's idea (same principle as `sort-object-types`: https://github.com/azat-io/eslint-plugin-perfectionist/pull/216

I have to admit that this implementation is indeed much cleaner than the one I mentioned here: https://github.com/azat-io/eslint-plugin-perfectionist/issues/197#issuecomment-2286385780

**Comment by hugop95** [comment]
> @hugop95, @azat-io, what do you think about making `groupKind` accepting more options, e.g.
> 
> ```
> groupKind: {
>   optionalElements: 'optional-first' | 'required-first' | 'mixed' // default: 'mixed'
>   decoratedElements: 'by-decorator-name-first' | 'by-element-name-first' // default: 'by-element-name-first'
>   ... // more options to come as needed
> }
> ```

I think that this is achievable with the official groups with have now? Maybe a bit more verbose than adding an option directly, but achievable.

**Comment by hugop95** [comment]
> @hugop95, @azat-io, what do you think about making `groupKind` accepting more options, e.g.
> 
> ```
> groupKind: {
>   optionalElements: 'optional-first' | 'required-first' | 'mixed' // default: 'mixed'
>   decoratedElements: 'by-decorator-name-first' | 'by-element-name-first' // default: 'by-element-name-first'
>   ... // more options to come as needed
> }
> ```

I don't know if the added complexity is worth it,  too much of a rare case indeed?

**Comment by OlivierZal** [comment]
Yes, I agree on that.

**Comment by hugop95** [comment]
Alternative PR adding the `optional` modifier to `property` and `accessor-property`:
https://github.com/azat-io/eslint-plugin-perfectionist/pull/219
