### ISSUE TITLE
Feature: `sort-enums` support sort by enum value instead of enum name

### ISSUE THREAD

**Issue by fkworld** [azat-io/eslint-plugin-perfectionist#200]
### What rule do you want to change?

sort-enums

### Describe the problem

For example, a numeric enums, I wish to sort by enum value, instead of enum name.

### Sort by enum value:
```ts
enum Direction {
  Up = 1,
  Down = 2,
  Left = 3,
  Right = 4,
}
```

### Sort by enum name:
```ts
enum Direction {
  Down = 2,
  Left = 3,
  Right = 4,
  Up = 1,
}
```

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Added in 285a4516e6ee3893d888e1f26fb75424af003efc.
Released in [v3.2.0](https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v3.2.0).
