### ISSUE TITLE
Feature: `sort-classes` Improved custom group system

### ISSUE THREAD

**Issue by hugop95** [azat-io/eslint-plugin-perfectionist#201]
### What rule do you want to change?

`sort-classes`

### Describe the problem

Improve the customGroups API by allowing an array of `CustomGroup` elements to be entered rather than an object. More information in PR: https://github.com/azat-io/eslint-plugin-perfectionist/pull/208

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Added in baa701d494baa8d01f977a650080fb52c61dbc46.
Released in [v3.2.0](https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v3.2.0).

**Comment by hugop95** [comment]
@azat-io Not yet implemented! 😄 Could you reopen please?

**Comment by azat-io** [comment]
Reopened.
