### ISSUE TITLE
Feature: Allow specifying cross-rule default settings 

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [azat-io/eslint-plugin-perfectionist#202]
### What rule do you want to change?

(all of them! 🤘)

### Describe the problem

I sometimes want to specify common options across all `perfectionist/*` rules. For example, I personally always enable `partitionByComment: true`. But in order to do that, right now I think I have to specify rule options manually -- which includes re-specifying anything non-default that was set in a config:

Example ESLint config snippet from https://github.com/typescript-eslint/typescript-eslint/pull/9698:

```ts
{
  ...perfectionistPlugin.configs['recommended-alphabetical'],
  files: ['packages/utils/src/**/*.ts'],
  rules: {
    ...perfectionistPlugin.configs['recommended-alphabetical'].rules,
    'perfectionist/sort-classes': [
      'error',
      {
        order: 'asc',
        partitionByComment: true,
        type: 'natural',
      },
    ],
    'perfectionist/sort-objects': [
      'error',
      {
        order: 'asc',
        partitionByComment: true,
        type: 'natural',
      },
    ],
  },
},
```

### Code example

It'd be nice if we could specify options like `partitionByComment: true` _once_ in [ESLint configuration shared settings](https://eslint.org/docs/latest/use/configure/configuration-files#configuring-shared-settings). That way we could avoid having to reconfigure individual rules to all adhere to our preferences.

Rough design proposal:

```ts
{
  ...perfectionistPlugin.configs['recommended-alphabetical'],
  files: ['packages/utils/src/**/*.ts'],
  settings: {
    perfectionist: {
      partitionByComment: true,
    }
  }
},
```

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
That's a good idea. Thanks, I'll take it to work.

**Comment by azat-io** [comment]
Added in 8e15730d5e3b8032ae1a7d6b5ad1f1f18b850ad2.
Released in [v3.2.0](https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v3.2.0)

**Comment by OlivierZal** [comment]
@azat-io, I’m trying to find and provide relevant / simple examples for deeper investigation, but it seems it doesn’t work when options are already set, e.g. with `perfectionist.configs['recommended-natural']` in https://github.com/OlivierZal/com.melcloud/blob/1f9637251b5e957d7fe166914b3fa9c664f0b689/eslint.config.mjs#L344

```
{
  rules: {
    'perfectionist/sort-named-export': [
      'error',
      {
        groupKind: 'types-first'
      }
    ]
  },
  settings: {
    ignoreCase: false
  }
}
```

**Comment by OlivierZal** [comment]
@azat-io, works great. Thanks!
