### ISSUE TITLE
Run on save with VSCode

### ISSUE THREAD

**Issue by its-monotype** [azat-io/eslint-plugin-perfectionist#21]
### Describe the bug

Hello! Is it possible to fix all rules when saving file somehow, I can't find anything in your docs about it so I just creating issue here, sorry for that

### Code example

-

### ESLint version

-

### ESLint Plugin Perfectionist version

-

### Validations

- [X] Read the [docs](https://eslint-plugin-perfectionist.azat.io).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Added more info to the documentation:
https://eslint-plugin-perfectionist.azat.io/guide/integrations
