### ISSUE TITLE
Bug: `sort-object-types` Optionality ignores the notion of group  

### ISSUE THREAD

**Issue by hugop95** [azat-io/eslint-plugin-perfectionist#217]
### Describe the bug

Optionality seems to be ignoring the notion of group:

### Code example

Configuration:

```
"perfectionist/sort-object-types": ["error", {
          "groupKind": "optional-first",
          "groups": [
            "callback",
            "unknown"
          ],
          "customGroups": {
            "callback": "on*"
          }
        }],
```

The following code below is invalid (`onClick` belongs to a group before `a`):
```ts
type A =  {
  a

  onClick
}
```

while this one is valid

```ts
type A =  {
  a?

  onClick
}
```

Is optionality supposed to be ignoring groups?

### ESLint version

8.57.0

### ESLint Plugin Perfectionist version

3.2.0

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Implemented in 8407bae.
Released in [v4.2.0](https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v4.2.0).
