### ISSUE TITLE
Multiple single line comments are misplaced after sort-objects

### ISSUE THREAD

**Issue by denis-sokolov** [azat-io/eslint-plugin-perfectionist#222]
### Describe the bug

`sort-objects` rule keeps comments that belong to a property with the property when that property is moved. This works for one line single-line comments and multi-line comments, but does not work for multiple lines of single-line comments.

### Code example

```js
const obj = {
  b: 1,
  // A long long explanation about the intricacies behind the decision
  // to make the value of property a here be 1
  a: 1
}
```

Actual:

```js
const obj = {
  // to make the value of property a here be 1
  a: 1,
  // A long long explanation about the intricacies behind the decision
  b: 1,
};
```

Expected:

```js
const obj = {
  // A long long explanation about the intricacies behind the decision
  // to make the value of property a here be 1
  a: 1,
  b: 1,
};
```

### ESLint version

v8.57.0

### ESLint Plugin Perfectionist version

v3.2.0

### Additional comments

Same applies to [sort-object-types](https://perfectionist.dev/rules/sort-object-types) and [sort-interfaces](https://perfectionist.dev/rules/sort-interfaces).

Prior art: [typescript-sort-keys/interface](https://www.npmjs.com/package/eslint-plugin-typescript-sort-keys) keeps multiple single-line comments together with the field.

(Thanks for a great tool, packaging all these rules into one clean plugin!)

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Duplicate #97
