### ISSUE TITLE
Docs: Explain & show examples of 'groups'

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [azat-io/eslint-plugin-perfectionist#223]
### Describe the rule

https://perfectionist.dev/rules/sort-union-types#groups exists that mentions what `groups` are... but I can't find any examples of how to use it on the docs site. Would you be up for adding some please?

Specifically, I'm coming over from https://github.com/typescript-eslint/typescript-eslint/pull/9698: we'd like to configure `null` and `undefined` to come last in our union types. This was previously available as a `nullable-last` option (https://github.com/azat-io/eslint-plugin-perfectionist/issues/61) but was removed in 3.0.0.

### Code example

```js
'perfectionist/sort-union-types': [
  'error',
  {
    groups: [ /* ??? */ ]
  }
]
```

### Additional comments

Sorry for using the wrong template 😅 there wasn't one I could find for docs / website stuff.

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by hugop95** [comment]
Specifically, I'm coming over from [typescript-eslint/typescript-eslint#9698](https://github.com/typescript-eslint/typescript-eslint/pull/9698): we'd like to configure `null` and `undefined` to come last in our union types.

This configuration should put `null` and `undefined` at the end of your types. `unknown` fits any other members from your union type.

```
"perfectionist/sort-union-types": ["error", {
          "groups": [
                "unknown",
                "nullish"
          ]
        }]
```

It would be a good idea to put the configuration linked to the example shown in the docs in the `Usage` section.
