### ISSUE TITLE
Bug: `sort-enums` breaks members referencing earlier members: "reference members declared after it,"

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [azat-io/eslint-plugin-perfectionist#226]
### Describe the bug

I'm seeing cases where `perfectionist/sort-enums` is asking to reorder an enum to be in alphabetical/natural order, even though an enum member has to go last to reference earlier members.

### Code example

```ts
enum ArgumentType {
  First = 1 << 0,
  RegExp = 1 << 1,
  Both = First | RegExp,
  //  ~~~~~~~~~~~~~~~~~ 
  // Expected "Both" to come before "RegExp". (eslint)
}
```

After fixing:

```ts
enum ArgumentType {
  Both = First | RegExp,
  First = 1 << 0,
  RegExp = 1 << 1,
}
```

```plaintext
$ npm run tsc

> repros@1.0.0 tsc
> tsc index.ts

index.ts:2:10 - error TS2651: A member initializer in a enum declaration cannot reference members declared after it, including members defined in other enums.

2   Both = First | RegExp,
           ~~~~~

index.ts:2:18 - error TS2651: A member initializer in a enum declaration cannot reference members declared after it, including members defined in other enums.

2   Both = First | RegExp,
                   ~~~~~~


Found 2 errors in the same file, starting at: index.ts:2
```

### ESLint version

9.0.0

### ESLint Plugin Perfectionist version

3.2.0

### Additional comments

Isolated repro: https://github.com/JoshuaKGoldberg/repros/tree/perfectionist-order-enums-self-referencing

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Fixed in eeb0534. Released in [v3.3.0](https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v3.3.0).
