### ISSUE TITLE
Bug(sort-classes): static section incorrectly placed before static properties definition

### ISSUE THREAD

**Issue by jerome-benoit** [azat-io/eslint-plugin-perfectionist#234]
### Describe the bug

static section incorrectly placed before static properties definition triggering JS runtime error. 

### Code example

Sorting done by `sort-classes` rule:

```ts
class A { 
  static {
    Configuration.cache = new Map<
      string,
      object
    >([
      ['foo', new Foo()],
      ['bar', new Bar()],
    ])
  }

  private static cache: Map<string, object>
}
```

### ESLint version

9.9.1

### ESLint Plugin Perfectionist version

3.3.0

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Released in [v3.4.0](https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v3.4.0).
