### ISSUE TITLE
Bug(sort-classes): Unattended sorting for method as arrow function

### ISSUE THREAD

**Issue by jerome-benoit** [azat-io/eslint-plugin-perfectionist#236]
### Describe the bug

Class with methods as arrow function do not seem to be sorted as part of the class methods. 

### Code example

I have not yet identified the minimum code to extract, but if you look at that class: https://github.com/SAP/e-mobility-charging-stations-simulator/blob/main/src/charging-station/Bootstrap.ts:

- The `logPrefix` method defined as arrow function is sorted with other properties at the beginning
- Other methods defined as arrow function are sorted before the constructor 

### ESLint version

9.9.1

### ESLint Plugin Perfectionist version

3.3.0

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by hugop95** [comment]
This is the expected behavior in today's version: the `function-property` selector is not part of any of the default `groups`, so those properties get matched with the `property` selector instead.

**Comment by jerome-benoit** [comment]
I fully agree with your proposal to group and sort methods and functions in classes in default configurations. 

The rationale being that using arrow function in class method is an implementation detail for the same primitive and it should not impact the class sorting of identical primitives.
Since it's a breaking change, is there an easy to just extends the existing default configuration of `sort-classes` with just different grouping?

**Comment by hugop95** [comment]
The default `groups` configuration itself is not extendable so I don't think that what you request is possible today: you need to copy the default `groups` configuration and make the changes afterward. 

Changing the default configuration will indeed affect all users using the default grouping. 
I don't know if in practice it is that big of an issue. Until recently, static blocks and accessor properties were put at the bottom of the file by default, so I assume a lot of users either have their own custom configuration or would understand the idea behind grouping methods and function properties together.

**Comment by azat-io** [comment]
Thank you for your issue. Added in 97adf510aac485b476715b619190947fdde7246e.
Released in [v4.0.0](https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v4.0.0).

If you'd like, you can support the release with a retweet:
https://x.com/azat_io_en/status/1858853714238271530
