### ISSUE TITLE
Bug: `sort-classes`: Function properties's body dependencies are not properly detected when tests say they should

### ISSUE THREAD

**Issue by hugop95** [azat-io/eslint-plugin-perfectionist#238]
### Describe the bug

Function properties's body dependencies are not properly detected.

### Code example

```ts
class Class {
  z = 10

  a = () => {
    return this.z;
  }
}
```

This code is considered invalid and requires property `a` to be before property `z`.

While having `a` before `z` will not cause issues at compile time nor at runtime, the current codebase and tests clearly indicate that the expected sorting should be `z` before `a` because `a`'s body depends on `z`.

This issue becomes more problematic with `static` blocks (see https://github.com/azat-io/eslint-plugin-perfectionist/issues/234).
In this case, body dependencies become relevant to ensure that code still compiles and runs correctly after sorting.

The tests associated to this issue do not work as expected. For example https://github.com/azat-io/eslint-plugin-perfectionist/blob/305d88c6a7a901321eaed5313edc13a9989d59f8/test/sort-classes.test.ts#L2671-L2681

This test does nothing, because the sort type is `alphabetical`, so `method` should come after `a` anyway.

Either:
- Function properties should ignore body dependencies because they do not actually require the properties they depend on to be before them.
- Or function properties should always be placed after their dependencies even if this does not impact compilation or runtime.

### ESLint version

8.57.0

### ESLint Plugin Perfectionist version

v3.3.0

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Fixed in e7c113d.
Released in [v3.4.0](https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v3.4.0).
