### ISSUE TITLE
Bug: `test` not working

### ISSUE THREAD

**Issue by abaran30** [azat-io/eslint-plugin-perfectionist#24]
### Describe the bug

With latest main (commit `0ed298f`), I am unable to run tests for the repo.

Steps to reproduce:
1. Follow instructions in contributing.md to clone the repo and install dependencies
2. (Optional): Modify a test so that it purposely fails
3. Attempt to run `npx pnpm test`

Output is as follows:
```
-> % npx pnpm test

> eslint-plugin-perfectionist@1.4.0 test /Users/adbaran/Development/GitHub/.temp/eslint-plugin-perfectionist
> pnpm run /^test:/


> eslint-plugin-perfectionist@1.4.0 test:js /Users/adbaran/Development/GitHub/.temp/eslint-plugin-perfectionist
> eslint "**/*.{js,ts}"


> eslint-plugin-perfectionist@1.4.0 test:types /Users/adbaran/Development/GitHub/.temp/eslint-plugin-perfectionist
> tsc --noEmit --pretty


> eslint-plugin-perfectionist@1.4.0 test:unit /Users/adbaran/Development/GitHub/.temp/eslint-plugin-perfectionist
> vitest --run --coverage --single-thread --no-threads


 RUN  v0.32.2 /Users/adbaran/Development/GitHub/.temp/eslint-plugin-perfectionist
      Coverage enabled with v8

 % Coverage report from v8
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |
----------|---------|----------|---------|---------|-------------------
include: **/__tests__/**/*.?(c|m)[jt]s?(x), **/?(*.){test,spec}.?(c|m)[jt]s?(x)
exclude:  **/node_modules/**, **/dist/**, **/cypress/**, **/.{idea,git,cache,output,temp}/**, **/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build}.config.*
watch exclude:  **/node_modules/**, **/dist/**

No test files found, exiting with code 1
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Test failed. See above for more details.
```

### Code example

N/A

### ESLint version

N/A

### ESLint Plugin Perfectionist version

N/A

### Validations

- [X] Read the [docs](https://eslint-plugin-perfectionist.azat.io).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
It's strange, I don't have this problem. What version of nodejs do you have? What operating system?

So far I have no idea what the problem could be.

<img width="902" alt="image" src="https://github.com/azat-io/eslint-plugin-perfectionist/assets/5698350/9079ba32-60ea-4351-ab6f-18bf9eec7e62">

**Comment by azat-io** [comment]
This problem seems to be caused by the name of the directory `.temp`

**Comment by abaran30** [comment]
Confirmed, that was indeed the issue. Thanks very much for the quick response!

**Comment by azat-io** [comment]
It may be worth creating an issue in the Vitest repo
