### ISSUE TITLE
Bug: `sort-classes`: Dependencies ignore the notion of `static`

### ISSUE THREAD

**Issue by hugop95** [azat-io/eslint-plugin-perfectionist#240]
### Describe the bug

Properties and static properties can coexist in the same class with the same name.

Dependencies extraction ignores the notion of `static` and may consider that `a` depends on `b` even if it's not the case.

### Code example

Group configuration
```
"groups": [
  ["property", "static-property"]
]
```

```ts
export class Class{
  b = 1;
  a = this.b;

  static b = 1;
}
```

This code is considered invalid (it is valid) and requires `static b` to be before `a` because it is considered a dependency of `a`. 

### ESLint version

8.57.0

### ESLint Plugin Perfectionist version

v3.3.0

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Fixed in e7c113d.
Released in [v3.4.0](https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v3.4.0).
