### ISSUE TITLE
Bug: `sort-classes`: Group configuration order takes precedence over dependencies

### ISSUE THREAD

**Issue by hugop95** [azat-io/eslint-plugin-perfectionist#241]
### Describe the bug

Group configuration order takes precedence over dependencies, resulting in code that does not compile.

### Code example

Group configuration
```
"groups": [
  "private-property",
  "public-property"
]
```

Code
```ts
class Class {
  public a = 1;
  private b = this.a;
}
```

This code is considered invalid and requires `b` to be before `a` due to the groups order specified in the configuration. This leads to code that does not compile because `b` depends on `a`.

### ESLint version

8.57.0

### ESLint Plugin Perfectionist version

v3.3.0

### Additional comments

This likely affects other rules that use both the notion of groups and dependencies.

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Fixed in e7c113d.
Released in [v3.4.0](https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v3.4.0).
