### ISSUE TITLE
Bug: `sort-classes`: Dependencies can cause undefined sorting behavior

### ISSUE THREAD

**Issue by hugop95** [azat-io/eslint-plugin-perfectionist#242]
### Describe the bug

The sorting algorithm sorts nodes by dependency relationships and other parameters (to sort by name, etc) in the same stage. This can lead to undefined sorting behavior:

### Code example

```ts
class Class {

  a = this.c

  b = 10

  c = 10

}
```

This code is considered valid when it should not, because `a` depends on `c`.
The issue arises from the fact that according to the sorting algorithm:
- `a` and `b` are independent, so `a` < `b` (alphabetical sort)
- `b` and `c` are independent, so `b` < `c` (alphabetical sort)

However, `a` depends on `c` so `c` < `a` (dependency-sort)

We get the following circular chain:
`a` < `b` < `c` < `a`

### ESLint version

8.57.0

### ESLint Plugin Perfectionist version

v3.3.0

### Additional comments

Theoretically affects other rules that use dependencies as well.

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Fixed in e7c113d.
Released in [v3.4.0](https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v3.4.0).
