### ISSUE TITLE
Bug: `sort-imports`: Inline comments prevent sorting

### ISSUE THREAD

**Issue by hugop95** [azat-io/eslint-plugin-perfectionist#252]
### Describe the bug

Comment blocks prevent adjacent import statements from being re-ordered:

```ts
  import { b1, b2 } from 'b'

  /**
   * Comment
   */

  import { a } from 'a'
  import { c } from 'c'
```
(Valid)

Removing the comment block and linting will result in the following:
```ts
    import { a } from 'a'
    import { b1, b2 } from 'b'
    import { c } from 'c'
```

However, replacing the comment block with an inline comment will also prevent sorting:

```ts
  import { b1, b2 } from 'b' // Comment

  import { a } from 'a'
  import { c } from 'c'
```
This is considered valid when it should not.

### Code example

See above.

### ESLint version

8.57.0

### ESLint Plugin Perfectionist version

v3.3.0

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Fixed in bd8ba3f. Released in [v3.6.0](https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v3.6.0).
