### ISSUE TITLE
Feature: Default level to "warn" not "error"

### ISSUE THREAD

**Issue by paullewisn** [azat-io/eslint-plugin-perfectionist#253]
### What rule do you want to change?

All

### Describe the problem

It would be great if the rules were all set to "warn" rather than "error" by default, or have a `recommended-alphabetical-warn` config. I currently override every one individually.

### Code example

```
const config: Linter.Config[] = [
  perfectionist["recommended-alphabetical"]
]
```

### Additional comments

Great plugin, thanks!

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Duplicate #221.

**Comment by paullewisn** [comment]
Thanks @azat-io, that is what I am currently doing 👍🏼
