### ISSUE TITLE
Bug: `sort-variable-declarations`

### ISSUE THREAD

**Issue by splincode** [azat-io/eslint-plugin-perfectionist#254]
### Describe the bug

```
error  'position' was used before it was defined  @typescript-eslint/no-use-before-define
```

when use

```json5
{
   '@typescript-eslint/no-use-before-define': 'error',
   'perfectionist/sort-variable-declarations': [
        'error',
        {
            ignoreCase: true,
            order: 'asc',
            type: 'alphabetical',
        },
    ]
}
```

### Code example

Before lint

```js
for (
    let position = editor.state.selection.$anchor,
        depth = position.depth;
    depth > 0;
    depth--
) {
// ... editor update state
}
```

After fix

```js
for (
    let depth = position.depth,
        position = editor.state.selection.$anchor;
    depth > 0;
    depth--
) {
// ... editor update state
}
```

### ESLint version

v8

### ESLint Plugin Perfectionist version

v4

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Fixed in 6beb536. Released in [v3.5.0](https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v3.5.0).
