### ISSUE TITLE
Feature: order function

### ISSUE THREAD

**Issue by splincode** [azat-io/eslint-plugin-perfectionist#261]
### Describe the rule

before

```ts
export function b() {
 // ..
}

export function c() {
 // ..
}

export function a() {
 // ..
}
```

### Code example

after

```ts
export function a() {
 // ..
}

export function b() {
 // ..
}

export function c() {
 // ..
}
```

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by hugop95** [comment]
I like the idea but think that it be extended to choosing how to sort file members in general rather than just functions (types, interfaces, classes etc).

**Comment by OlivierZal** [comment]
I agree with @hugop95 it could be with anything: constants, arrow functions, etc.

The difficulty is to pay attention whether they are dependent one with the others, to avoid calling "something" before its declaration.

**Comment by azat-io** [comment]
It seems to me that this would be extremely difficult to implement.
