### ISSUE TITLE
Bug: a.options.at is not a function

### ISSUE THREAD

**Issue by IlyaTsokota** [azat-io/eslint-plugin-perfectionist#27]
### Describe the bug

```
[eslint] a.options.at is not a function
Occurred while linting checkFileExtension.js:14
Rule: "perfectionist/sort-array-includes"
```

swears like this at all rules, except for the rules regarding types

### Code example

pops up on perfectly normal lines without any problems
https://i.imgur.com/tEjtt92.png

### ESLint version

v8.34.0

### ESLint Plugin Perfectionist version

v1.4.0

### Validations

- [X] Read the [docs](https://eslint-plugin-perfectionist.azat.io).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
`Array.prototype.at()` supports by Node.js v16.6.0+
What version of Node.js are you using?

**Comment by IlyaTsokota** [comment]
v14.21.2

Thanks for the help! Update to latest stable
