### ISSUE TITLE
Docs: Typo in `sort-array-includes` page

### ISSUE THREAD

**Issue by brandongit2** [azat-io/eslint-plugin-perfectionist#279]
### Describe the bug

https://perfectionist.dev/rules/sort-array-includes#groupkind mentions the `spread-first` setting. This should be `spreads-first`: https://github.com/azat-io/eslint-plugin-perfectionist/blob/c66eb4cf6c0be992cb219df62189c2a8cae24121/rules/sort-array-includes.ts#L51

### Code example

Incorrect (causes error):

```js
"perfectionist/sort-array-includes": ["warn", {groupKind: "spread-first"}],
```

Correct:

```js
"perfectionist/sort-array-includes": ["warn", {groupKind: "spreads-first"}],
```

### ESLint version

9.11.0

### ESLint Plugin Perfectionist version

3.6.0

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Thanks! Fixed in efa27509a7f9f1b96e068631cc74c3aa155f2d45.
