### ISSUE TITLE
Bug: sort-imports rule does not sort external-type and sibling-type correctly in the same group

### ISSUE THREAD

**Issue by jasonneylon** [azat-io/eslint-plugin-perfectionist#295]
### Describe the bug

Hi,

When I configure the `sort-imports` rule with a group for type imports where external types come before sibling types the rule is not followed. Instead, eslint reports valid code as violating the rule.

Thanks 🙏 

### Code example

eslint config:

```javascript
    'perfectionist/sort-imports': [
      "error",
      {
        "groups": [
          [
            "builtin-type",
            "external-type",
            "index-type",
            "internal-type",
            "parent-type",
            "sibling-type",
            "type"
          ]
        ]
      }
    ]
```

When I lint the following code with this rule configuration:

```typescript
import type { ReactNode } from 'react';
import type { Test } from './othertypes';
```

I get a lint error as follows:
```
/Users/jneylon/babbel/lessonnine/perfectionisteslint-config-test/src/types.ts
  2:1  error  Expected "./othertypes" to come before "react"  perfectionist/sort-imports

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
```

Given the rule configuration above I would expect this code to be valid.

There is a minimal reproduction in this repo: https://github.com/jasonneylon/perfectionist-eslint-config-test/tree/main

### ESLint version

8.57.1

### ESLint Plugin Perfectionist version

3.7.0

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by hugop95** [comment]
Hello @jasonneylon !

It seems that there might be a typo in your configuration: you nest your groups in another array
```json
    'perfectionist/sort-imports': [
      "error",
      {
        "groups": [
          [
             ...
          ]
        ]
      }
    ]
```

instead of

```json
    'perfectionist/sort-imports': [
      "error",
      {
        "groups": [
             ...
        ]
      }
    ]
```

What your initial configuration does is put all of your groups into the same group, which means that your two imports are now sorted alphabetically.

**Comment by jasonneylon** [comment]
Hi @hugop95 

What I'm trying to do is sort imports first into a non-types imports and then into type imports, so there is more configuration in our actual use case than included above.

The full configuration is here: https://github.com/babbel/eslint-config/blob/190a48d5830e40116800955ed02ed5aabff39813/lib/eslintBaseConfig.json#L43-L64

```json
    "perfectionist/sort-imports": [
      "error",
      {
        "environment": "node",
        "groups": [
          ["side-effect", "side-effect-style"],
          ["builtin", "external"],
          ["index", "internal", "parent", "sibling", "unknown"],
          "object",
          [
            "builtin-type",
            "external-type",
            "index-type",
            "internal-type",
            "parent-type",
            "sibling-type",
            "type"
          ],
          "style"
        ]
      }
    ],
```

So I expected this code to be valid according to the `sort-imports` rule.
```
import { test } from './test';

import type { ReactNode } from 'react';
import type { Test } from './othertypes';
```

i.e. non type import would come first in one group and type imports would be in a second group **sorted in the order specified in that group**.

> What your initial configuration does is put all of your groups into the same group, which means that your two imports are now sorted alphabetically.

I understand from your comment that the rules work differently than I thought and that sorting within a group is done alphabetically and not by the order of the import types specified in the group configuration. Is that how `sort-imports` works?

Thanks!

**Comment by hugop95** [comment]
@jasonneylon I see now. 

You understand correctly: the order in "nested" groups is not taken into account. Each nested group behaves like any other normal group would: members within that nested group get all grouped together and get sorted alphabetically.

I believe that not nesting the type imports could give you the sorting you want ? Although the spacing requirements between imports will now be different, as elements that previously were in the same group now aren't.
