### ISSUE TITLE
Bug: perfectionist/sort-objects customGroups strange behavior

### ISSUE THREAD

**Issue by deathemperor** [azat-io/eslint-plugin-perfectionist#296]
### Describe the bug

custom groups are not sorted as configured

config:
```js
        "perfectionist/sort-objects": [
          "error",
          {
            ignoreCase: false,
            groups: ["dates"],
            customGroups: {
              dates: ["startDate", "endDate", "start_date", "end_date"],
            },
          },
        ],
```

![image](https://github.com/user-attachments/assets/60bb4a87-5d7f-4de3-b878-5fc129003968)

### Code example

https://github.com/deathemperor/perfectionist-custom-groups

### ESLint version

8.57.0

### ESLint Plugin Perfectionist version

3.6.0

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by hugop95** [comment]
Hi @deathemperor,

The expected result with your configuration is  
```ts
const test = {
  end_date: "2021-01-02",
  endDate: "2021-01-02",
  start_date: "2021-01-01",
  startDate: "2021-01-01",
};
```

which seems to be working as intended.

What result are you expecting?

**Comment by deathemperor** [comment]
thanks for the explanation, it works. I find it confusing setting up group & customGroups.

What does `top` array mean in this example from the docs?

```ts
{
   groups: [
    'top',
     'unknown',
   ],
  customGroups: {       
    top: ['id', 'name'] 
  }                     
 }
```

**Comment by hugop95** [comment]
@deathemperor I understand that customGroups and groups can be easily misconfused: they represent very different thing.

### groups
`groups` represent the sorting order of the elements: elements matching the `top` group will be put above elements matching the `unknown` group.

### customGroups
`customGroups` are actually **custom groups definitions**. With the exception of `sort-classes` which has a more advanced API, keys of the `customGroups` field are the **names** of groups that you should put in `groups`, and the values are:
- if a string, what the element's name need to match to be part of the group.
- if an array, the element's name need to match at least one of the elements of the array to be part of the group. Matching is by default using https://github.com/isaacs/minimatch.

With the example above, this means that for the object
```js
const a = {
    a: 'a',
    id: 'myId',
    _name: 'name',
    b: 'b'
}
```

- `a` matches the `unknown` group (the default group given when an element doesn't match any group referenced in `groups`).
- `id` includes `id` so it matches the `top` group.
- `_name` matches `name` so it matches the `top` group.
- `b` matches the `unknown` group.

The result you should get is:

```js
const a = {
    id: 'myId',
    _name: 'name',
    a: 'a',
    b: 'b'
}
```

Elements within the same group are sorted alphabetically/naturally depending on your configuration.

I hope this makes things a bit clearer, I think that `groups` and `customGroups` are features that we should improve a bit regarding the documentation as some concepts are not easy to understand at first.
