### ISSUE TITLE
How Can I Prevent `sort-classes` from Reordering Class Properties Incorrectly with `perfectionist`?

### ISSUE THREAD

**Issue by jon9090** [azat-io/eslint-plugin-perfectionist#300]
I have the following code:

```js
function createState(cb) {
  function set() { ... }
  cb(set);
}

function querystring() {
    return { value: '...' }
}

class Foo {
   querystring = createQueryString();

   state = createState((set) => {
      set('query', this.queryString.value);
   });
}
```

When I run the `sort-classes` rule with `recommended-alphabetical`, it gets changed to:

```js
class Foo {
   state = createState((set) => {
      set('query', this.queryString.value);
   });
   querystring = createQueryString();
}
```

The issue is that `querystring` must be initialized before `state`. otherwise there is a runtime error. ` this.queryString.` undefined.

Is there a way to fix this using `perfectionist`?

### ESLint version

^9.8.0

### ESLint Plugin Perfectionist version

latest

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by hugop95** [comment]
Hi @jon9090, this is something that needs to be fixed on the plugin side, it shouldn't take long. In the meantime, you can use customGroups to force querystring to be before anything else.
