### ISSUE TITLE
How to configure sort-interfaces rule to sort properties first and then methods

### ISSUE THREAD

**Issue by Marko-Matijevic** [azat-io/eslint-plugin-perfectionist#305]
### Describe the rule

Hello, this is not a new rule proposal but a question is there a possibility to sort attributes first and then methods?

// WRONG 
interface Props {
    onOpenUrl: () => void;
    url: string;
}

// CORRECT 
interface Props {
    url: string;
    onOpenUrl: () => void;
}

### Code example

"perfectionist/sort-interfaces": [
            "error",
            {
                "type": "alphabetical", 
                "order": "asc",     
                "groups": [
                    "attributes",    
                    "methods"              
                ],
                "matcher": 'regex',
                "customGroups": {
                    "attributes": "^(?!.*\\(.*\\))",  // Matches properties that do not have parentheses, indicating they are not functions
                    "methods": "^.*\\(.*\\)$"          // Matches properties that have parentheses, indicating they are functions 
                }
            }
        ]

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Thank you for your issue! I'll add predefined group for functions soon.

**Comment by azat-io** [comment]
Added in b797371.
Releases in [v3.9.0](https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v3.9.0).
