### ISSUE TITLE
Feature: distinguish TypeScript non-relative imports relative to 'baseSrc' as a separate group in 'sort-imports' rule

### ISSUE THREAD

**Issue by gavvvr** [azat-io/eslint-plugin-perfectionist#317]
### What rule do you want to change?

sort-imports

### Describe the problem

In TypeScript, instead of `import`ing files relative to your current `.ts` file ('parent', 'sibling'), you can also use non-relative import style (which will be relative to a directory specified in `baseUrl` in `tsconfig.json`).

Since eslint-plugin-perfectionist project [also has `baseUrl` specified](https://github.com/azat-io/eslint-plugin-perfectionist/blob/v3.8.0/tsconfig.json#L15), then instead of `import sortVariableDeclarations from './rules/sort-variable-declarations'`, the source code might say: `import sortVariableDeclarations from 'rules/sort-variable-declarations'`

The problem is that TypeScript non-relative imports are treated as those belonging to 'external' group.

Would be great to distinguish them as a separate group. I would prefer to group 'ts-non-relative-imports' together with 'parent', 'sibling' and 'index'.

### Code example

To see in practice what I mean, do the following

1. Clone this repo on the latest version `git clone --branch v3.8.0 https://github.com/azat-io/eslint-plugin-perfectionist`
2. Navigate to `./index.ts` and convert one relative import to non-relative one: (for example, replace `from './rules/sort-variable-declarations'` with `from 'rules/sort-variable-declarations'`, notice the `./` got removed)
3. Apply eslint `--fix` on this file and you'll see that `from 'rules/sort-variable-declarations'` import will belong to a separate group. 

You can easily ensure that it gets treated as 'external' if you 

1) add a couple more different imports, for example:
```typescript
import {readFileSync} from 'node:fs' // 'builtin'
import naturalCompare from 'natural-compare-lite' // 'external'
```
2) and also configure `perfectionist/sort-imports` rule to split 'external' and 'builtin' into separate groups

If you configure 'builtin' and 'external' to belong separate groups, then `from 'rules/sort-variable-declarations'` will be grouped with `from 'natural-compare-lite'` (which is 'external' for this project)

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by hugop95** [comment]
Hi @gavvvr ,

I like the idea. The way I see it, this theoretically requires, for each file linted, to:
1. Detect the nearest `tsconfig.json`
2. Read it
3. Parse it (read `extends`) to determine the actual `baseUrl `. 
4. For each import determine if it is an external import or a `ts-non-relative-imports`.

Nothing too complicated, but I do wonder if there would be some performance impact on large codebases?

**Comment by gavvvr** [comment]
Hi @hugop95 

Got your idea.
At first glance, it sounds as something, which can be implemented without significant efforts.

Although, yesterday I've also learned that besides this simple `baseUrl` logic, there is also a [`paths`](https://www.typescriptlang.org/tsconfig/#paths) re-mapping (with which things get a little bit more complicated). Hoping there are no more caveats, but I can easily imagine other module-loading tricks possible in TypeScript which I'm simply not aware of. Actually, I've learned about both (`baseUrl` and `paths`) just yesterday, when was applying eslint-plugin-perfectionist rule to my codebase 😅

So, some research is required to understand if there other ways for non-relative imports besides the [`baseUrl`](https://www.typescriptlang.org/tsconfig/#baseUrl) and [`paths`](https://www.typescriptlang.org/tsconfig/#paths)

**Comment by azat-io** [comment]
We had a similar feature, but gave it up because of performance issues. The process of reading tsconfig.json slowed down the plugin and almost nobody used this feature.

https://github.com/azat-io/eslint-plugin-perfectionist/commit/cccced1

We should think if there is any way we can do this effectively.

**Comment by hugop95** [comment]
I think that in theory, there is also more than just reading one `tsconfig.json` file. Two linted files may not depend on the same `tsconfig.json`.

We could cache results so we don't need to read the appropriate `tsconfig.json` for each file, similarly to how `typescript-eslint` does it: https://typescript-eslint.io/blog/parser-options-project-true/.

The question is, if, as said above, this feature is not used that much, is it worth adding this extra layer of complexity? I think that custom groups can (in a less convenient way, maybe) can be setup to fix this case.

**Comment by hugop95** [comment]
@azat-io @gavvvr

I have made tests regarding searching and reading the appropriate `tsconfig.json` file in large projects. 

I used an implementation identical to what exists in `typescript-eslint` (https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/typescript-estree/src/parseSettings/getProjectConfigFiles.ts). Their algorithm is very efficient and pretty much searches for a `tsconfig` only once per directory, so performance wise, I think that this here should be no major issue with a proper implementation.

There is something I don't understand, however, https://github.com/azat-io/eslint-plugin-perfectionist/commit/cccced1 removed the previous implementation for performance reasons, but I would like to understand how were the performance issues detected.
- Running ESLint through the CLI would read the `tsconfig.json` file once, so this should not cause issues?
- In the IDE, changing the file and saving may run ESLint for that file, which will trigger a read. Is this where the performance issues come from?

**Comment by azat-io** [comment]
@hugop95 If I remember correctly, the reading of `tsconfig.json` (in old implementation) happened every time the rule function was called, for each file.

**Comment by hugop95** [comment]
@azat-io Thanks.

I have made new tests with a build from c748445ff866a94036ace2fb36fc9f3f342ce75e.
The config is read once, and the performance impact of reading that file once is negligible, so this looks good to me.

Here are the results of that old build on a very large codebase (only `typescript-eslint` rules and `sort-import` were kept:
![image](https://github.com/user-attachments/assets/9396a0d2-bbcd-46cb-9441-66fc43d808b9)

While there are improvements to be made with how parsing is done (handling multiple `tsconfig.json` files, etc), I don't think that we would see that many changes performance-wise in comparison to c748445ff866a94036ace2fb36fc9f3f342ce75e.

The only thing I can think of is trying to share the cache between different ESLint runs (unsure if it's possible, haven't looked into that yet), which in that case would remove some stress on IDEs that would do a lot of runs in a short time).

**Comment by azat-io** [comment]
That sounds good.

In that case, I have no questions. Let's do this feature.
