### ISSUE TITLE
Bug(`sort-switch-case`): Switch cases cannot be sorted when switch expression isn't a value

### ISSUE THREAD

**Issue by anthony-j-castro** [azat-io/eslint-plugin-perfectionist#326]
### Describe the bug

First off, thank you for addressing the other issue I raised so quickly! When testing the new release with the fix, I encountered a new issue with `sort-switch-case`: if the switch expression is anything other than a simple value or variable (basically anything that requires evaluating such as a function call, accessing an object property, or a math expression), the cases are not recognized as being out of order.

### Code example

**Input**
```js
switch ("a".concat("", "b")) {
  case "b":
    break;
  case "c":
    break;
  case "ab":
    break;
}

const obj = {
  letter: "a",
};

switch (obj.letter) {
  case "b":
    break;
  case "c":
    break;
  case "a":
    break;
}

switch (1 + 2) {
  case 3:
    break;
  case 1:
    break;
  case 2:
    break;
}
```

**Expected Output**
```js
switch ("a".concat("", "b")) {
  case "ab":
    break;
  case "b":
    break;
  case "c":
    break;
}

const obj = {
  letter: "a",
};

switch (obj.letter) {
  case "a":
    break;
  case "b":
    break;
  case "c":
    break;
}

switch (1 + 2) {
  case 1:
    break;
  case 2:
    break;
  case 3:
    break;
}
```

**Actual Output**
(No change)
```js
switch ("a".concat("", "b")) {
  case "b":
    break;
  case "c":
    break;
  case "ab":
    break;
}

const obj = {
  letter: "a",
};

switch (obj.letter) {
  case "b":
    break;
  case "c":
    break;
  case "a":
    break;
}

switch (1 + 2) {
  case 3:
    break;
  case 1:
    break;
  case 2:
    break;
}
```

### ESLint version

9.12.0

### ESLint Plugin Perfectionist version

3.9.0

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Fixed in 3fb34fc.
Released in [v3.9.1](https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v3.9.1).
