### ISSUE TITLE
Bug: "sort-interfaces" is ignoring nested objects

### ISSUE THREAD

**Issue by johnjspiteri** [azat-io/eslint-plugin-perfectionist#332]
### Describe the bug

The rule works properly for the first level, any levels deeper are ignored.

With the simplest configuration, the deeper values are erroring as unordered.

```typescript
'perfectionist/sort-interfaces': 'error',
```

With a more robust configuration, the root level and deeper values are not sorting or erroring when unordered.

```typescript
'perfectionist/sort-interfaces': [
	'error',
	{
		type: 'alphabetical',
		order: 'asc',
		ignoreCase: true,
		specialCharacters: 'keep',
		ignorePattern: [],
		partitionByComment: false,
		partitionByNewLine: false,
		optionalityOrder: 'ignore',
		matcher: 'minimatch'
	}
],
```

With a simply array oriented configuration, the root level are sorting and deeper values are not sorting or erroring when unordered.

```typescript
'perfectionist/sort-interfaces': [
	'error',
	{}
],
```

or

```typescript
'perfectionist/sort-interfaces': [
	'error'
],
```

### Code example

Working on root level:

```typescript
interface Test {
	c: 'value',
	a: 'value',
	e: 'value',
	b: 'value',
	d: {
		a: 'value',
		b: 'value',
		c: 'value'
	},
	f: 'value'
}
```

will render

```typescript
interface Test {
	a: 'value',
	b: 'value',
	c: 'value',
	d: {
		a: 'value',
		b: 'value',
		c: 'value'
	},
	e: 'value',
	f: 'value'
}
```

Deeper than root level, will remain unchanged:

```typescript
interface Test {
	a: 'value',
	b: 'value',
	c: 'value',
	d: {
		b: 'value',
		c: 'value',
		a: 'value'
	},
	e: 'value',
	f: 'value'
}

```

### ESLint version

v9.12.0

### ESLint Plugin Perfectionist version

v3.9.0

### Additional comments

I commented out all other plugins and rules, to prevent any other possibly conflicting rules...

Super project and work, TY to everyone involved.

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by hugop95** [comment]
Hi @johnjspiteri,

Nested objects in interfaces are actually not handled by `sort-interfaces`, but `sort-object-types` instead.

![image](https://github.com/user-attachments/assets/39fa16ee-946a-40bb-9a2e-df23561f810c)


Enabling this rule and passing the same options as `sort-interfaces` should give you the expected result.
