### ISSUE TITLE
Bug(multiple-rules): Inline element sorting may result in fix that breaks compilation/runtime

### ISSUE THREAD

**Issue by hugop95** [azat-io/eslint-plugin-perfectionist#336]
### Describe the bug

This issue is related to inline sorting, and affects:
- `sort-classes`
- `sort-interfaces`
- `sort-object-types`
- `sort-imports`
- `sort-exports`
- `sort-switch-case` 

### Code example

```js
type Type = {
  b, a
}
```

This results in the following autofix, which breaks compilation:

```js
type Type = {
  a b,
}
```

Inlining `}` with the last member will make the rule work however:

```js
type Type = {
    a, b }
```
Even worse:

```js
type Type = {
  b,a
}
```

will get sorted into

```js
type Type = {
  ba,
}
```

Other example with `sort-classes`:

```ts
class Class {

    method(){}property: string

}
```

This is ugly, but it compiles and runs! It gets formatted into

```ts
class Class {

    property: stringmethod(){}

}
```

### ESLint version

8.57.0

### ESLint Plugin Perfectionist version

3.9.1

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Fixed in a3804b81fdf48d0672645e5c21fd61061711f25e.
Released in [v4.0.0](https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v4.0.0).

Thank you!
