### ISSUE TITLE
Feature: Merge duplicate imports

### ISSUE THREAD

**Issue by DenniLa2** [azat-io/eslint-plugin-perfectionist#340]
### Describe the rule

Thank you for the excellent 'perfectionist' plugin!
I've found it very helpful in improving the readability of my code. However, I've noticed that when I have multiple imports from the same module, they are not always grouped together. 

### Code example

before:
```ts
import type { FormItemRule } from 'naive-ui'
import type { FormRules } from 'naive-ui'
```

after:
```ts
import type {  FormItemRule, FormRules } from 'naive-ui'
```

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by hugop95** [comment]
Hi @DenniLa2,

If I understand correctly, you are expecting `import type { FormItemRule } from 'naive-ui'` and `import type {  FormItemRule, FormRules } from 'naive-ui'` to be imported together as `import type {  FormItemRule, FormRules } from 'naive-ui'` after linting.

`eslint-plugin-perfectionist` does not handle that. Instead, you can look at the `no-duplicate-imports` rule from ESLint: https://eslint.org/docs/latest/rules/no-duplicate-imports.

**Comment by azat-io** [comment]
Yes. As @hugop95 said, this is out of scope of the plugin.
