### ISSUE TITLE
Bug(sort-switch-case): Invalid comment placement with consecutive cases

### ISSUE THREAD

**Issue by hugop95** [azat-io/eslint-plugin-perfectionist#343]
### Describe the bug

See code example.

### Code example

```ts
switch(name) {
  case 'b': // b
  case 'a': // a
    return
}
```

Result:

```ts
switch(name) {
  case 'a':
  case 'b': // a
    return // b
}
```

### ESLint version

8.57.0

### ESLint Plugin Perfectionist version

3.9.1

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Added in 140c2c858ce6bed5ea0bac57f2cc3e4d9b6897fe.
Released in [v4.0.0](https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v4.0.0).
