### ISSUE TITLE
Bug: `perfectionist/sort-jsx-props` does not respect `ignoreCase`

### ISSUE THREAD

**Issue by grinkus-adapt** [azat-io/eslint-plugin-perfectionist#344]
### Describe the bug

No matter which option I use (`true` or `false`) for the `ignoreCase` value, it doesn't seem to change anything, I always get an error:
```
41:17  error  Expected "className" to come before "Component"
perfectionist/sort-jsx-props
```

**Edit:** I have `react/jsx-sort-props` switched off.

I couldn't find an issue already filled for this, but I'm not totally sure I know what to look for. Sorry if it's a duplicate.

### Code example

```eslint.config.js
  {
    ...perfectionistPlugin.configs[`recommended-alphabetical`],
    rules: {
      ...perfectionistPlugin.configs[`recommended-alphabetical`].rules,
      "perfectionist/sort-jsx-props": [`error`, { ignoreCase: false }],
    },
  },
```

 or 

```eslint.config.js
  {
    ...perfectionistPlugin.configs[`recommended-alphabetical`],
    rules: {
      ...perfectionistPlugin.configs[`recommended-alphabetical`].rules,
      "perfectionist/sort-jsx-props": [`error`, { ignoreCase: true }],
    },
  },
```

results in the same error

### ESLint version

9.13.0

### ESLint Plugin Perfectionist version

3.9.1

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by hugop95** [comment]
Hi @grinkus-adapt, `eslint-plugin-perfectionist` currently uses `localeCompare` to compare strings.

Assuming you are using an english locale, lowercase characters are sorted before uppercase characters, so the behavior is as expected here.

However, this is interesting to know that users are looking for this use case.

**Comment by hugop95** [comment]
You may use the `type: natural` alongside `ignoreCase: false` to get the result you expect however.

**Comment by grinkus-adapt** [comment]
Hi, thanks for replying so quick, @hugop95!

Setting `type: natural` indeed gets the result I expect.

First I thought I simply misread the docs, but while they're not strictly incorrect, they are a bit confusing. The docs state that setting `false` makes eslint consider case when sorting (e.g., **“A” comes before “a”** [emphasis mine]). Maybe wording could be tweaked a bit, or this caveat with the `localeCompare` could be mentioned. I don't mean this as a negative criticism, just a thought that might help.

![image](https://github.com/user-attachments/assets/8a697110-3ece-4cb7-bb93-f9a8b25168d5)

**Comment by grinkus-adapt** [comment]
@hugop95 a follow up question.

Is there a simple way to set `ignoreCase: false` for all rules in the `recommended-natural` config?

**Comment by hugop95** [comment]
@grinkus-adapt You are right regarding the documentation, this will be fixed for next version!

> Is there a simple way to set `ignoreCase: false` for all rules in the `recommended-natural` config?

Yes, you can use eslint `settings`:

```
      "settings": {
        "perfectionist": {
          "ignoreCase": false
        }
      },
      "rules": {
        "perfectionist/sort-interfaces": ["error"]
      }
```
