### ISSUE TITLE
Bug(sort-switch-case): Empty last case is sorted when it should not

### ISSUE THREAD

**Issue by hugop95** [azat-io/eslint-plugin-perfectionist#348]
### Describe the bug

See code example

### Code example

```ts
function funct(x) {
    switch(x) {
        case "b":
            // Do something
            break;
        case "a":
    }
}
```

This will result in

```ts
function funct(x) {
    switch(x) {
        case "a":
        case "b":
            // Do something
            break;
    }
}
```

### ESLint version

8.57.0

### ESLint Plugin Perfectionist version

3.9.1

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Added in 0cf84aef8fd8a33d843e4be445aaa4896e519b67.
Released in [v4.0.0](https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v4.0.0).
