### ISSUE TITLE
Feature: add `reservedFirst` option for `sort-jsx-props`

### ISSUE THREAD

**Issue by rakleed** [azat-io/eslint-plugin-perfectionist#353]
### What rule do you want to change?

sort-jsx-props

### Describe the problem

In React documentation, preserved properties (like `key`, `ref`, `children`, `dangerouslySetInnerHTML`) [are](https://react.dev/reference/react/useCallback#:~:text=%3CReport%20key%3D%7Bitem.id%7D%20item%3D%7Bitem%7D%20/%3E) [often](https://react.dev/reference/react/useMemo#:~:text=%3CReport%20key%3D%7Bitem.id%7D%20item%3D%7Bitem%7D%20/%3E) [listed](https://react.dev/reference/rules/components-and-hooks-must-be-pure#:~:text=.push(-,%3CFriend%20key%3D%7Bfriend.id%7D%20friend%3D%7Bfriend%7D%20/%3E,-)%3B%20//%20%E2%9C%85%20Good) [first](https://react.dev/reference/react/cloneElement#:~:text=isHighlighted%29%20%3D%3E-,%3CRow,/%3E,-%7D), and then all other properties. It would be nice to have a `reservedFirst` option, which would sort the preserved properties alphabetically first, and then all other properties when sorting properties. An example of a similar option: https://eslint.style/rules/jsx/jsx-sort-props#reservedfirst

### Code example

```js
function FriendList({ friends }) {
  const items = [];
  for (let i = 0; i < friends.length; i++) {
    const friend = friends[i];
    items.push(
      <Friend key={friend.id} friend={friend} />
    );
  }
  return <section>{items}</section>;
}
```

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by hugop95** [comment]
Hi @rakleed 

Is this really better than using `groups` and `customGroups`?

```ts
{
    groups: ['reserved', 'unknown'],
    customGroups: {
        reserved: ['key', 'ref'],
    },
```

This method allows greater customization of what "reserved words" should come first (or later) in my opinion.

**Comment by azat-io** [comment]
As @hugop95 said, we already have the functionality to realize this task - it's `groups`. You can create your own custom groups however you want.

We don't plan to add special `reserveredFirst` or `reserveredLast` options. Everything you want is already in the group.
