### ISSUE TITLE
Bug(sort-modules): Specific `export decorated` classes not handled correctly 

### ISSUE THREAD

**Issue by hugop95** [azat-io/eslint-plugin-perfectionist#376]
### Describe the bug

ESLint's parser doesn't seem to detect the decorator ranges correctly with the following syntax:

### Code example

```ts
class B {}

@A
export class A {}
```

This will result in

```ts
export class A {}

@A
class B {}
```

Removing `export` will make it work correctly.

Writing 

```ts
class B {}

export @A class A {}
```

will also make it work, but this is not an usual syntax.

### ESLint version

4.0.0

### ESLint Plugin Perfectionist version

8.57.0

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Released in [v4.0.1](https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v4.0.1).
