### ISSUE TITLE
Bug: Upgrading to v4, named imports are getting rearranged

### ISSUE THREAD

**Issue by aeharding** [azat-io/eslint-plugin-perfectionist#384]
### Describe the bug

---

With the following v3.9.1:

```
"perfectionist/sort-named-imports": [
  "warn",
  { ignoreCase: false, type: "natural", ignoreAlias: false },
],
```

```
import { LOCALSTORAGE_KEYS, get } from "#/features/settings/syncStorage";
```

✅ Valid

---

v4.0.2:

❌ `Expected "get" to come before "LOCALSTORAGE_KEYS".eslint[perfectionist/sort-named-imports](https://perfectionist.dev/rules/sort-named-imports)`

---

### Code example

See above

### ESLint version

v9.15.0

### ESLint Plugin Perfectionist version

v4.0.2

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by hugop95** [comment]
Hi @aeharding,

I haven't taken a deeper look yet, but I believe that this is likely due to the following breaking change:
- Move from `natural-compare-lite` to `natural-orderby`.

The implementation of natural sort is different. You may play with `ignoreCase` to try to get your previous order.

**Comment by hugop95** [comment]
`natural-orderby`:
```ts
console.log(naturalCompare('LOCALSTORAGE_KEYS', 'get')) // 1
```

`natural-lite`:
```ts
console.log(naturalCompare('LOCALSTORAGE_KEYS', 'get')) // -1
console.log(naturalCompare('lOCALSTORAGE_KEYS', 'get')) // 1
```

**Comment by azat-io** [comment]
This seems to be a question for [natural-orderby](https://github.com/yobacca/natural-orderby).
Perhaps we should create an issue about case sensitivity support for this project.

**Comment by Sparticuz** [comment]
Another difference that came up for me was that it seemed to put special characters before, so `eslint-comments.js` was moved before `eslint.js`

Before:
```ts
import eslintJSConfig from "./configs/eslint.js";
import eslintCommentsConfig from "./configs/eslint-comments.js";
```

After:
```ts
import eslintCommentsConfig from "./configs/eslint-comments.js";
import eslintJSConfig from "./configs/eslint.js";
```

**Comment by sthenault** [comment]
ooops wrong ping BTW, rather meant to call for @aeharding feedback

**Comment by sthenault** [comment]
may be related somewhat to 
```
l = ["a", "A"]
l.sort() -> [ "A", "a" ]
l.sort((a,b) => a.localeCompare(b)) ->  [ "a", "A" ]
```
? As it doesn't seem to have option providing backward compat, I suppose I have to update my imports order?

Wondering how this may have been unreported yet so I'm may be mistaken somewhere, though it seems that "sort-import" tests don't cover `ignoreCase: false`.

**Comment by hugop95** [comment]
@sthenault There is a discussion regarding this in #275.

There is no regression with the alphabetical sort and ignoreCase: it's just that the way ignoreCase and locale compare work together is misleading: it has almost no effect with this sorting algorithm.

Ultimately, the issue is that all of those different sorting algorithms are opinionated, and sometimes, options are not enough to customise them: some users would like to have capital letters take priority over lowercases ones, others would like certain special characters before others, so I'm aiming to offer a way to add custom sorting algorithms.

**Comment by sthenault** [comment]
@hugop95 thank you for your reply. I understand the problem under the cover now. If I use 'alphabetical' instead of 'natural' with 3.9.1, then it also considers that 'a' should come before 'A', while 'natural' expect the opposite... There is indeed no regression in v4 on this topic. 

Maybe because I'm too old and expect ascii order I missed that possibility ;)

**Comment by azat-io** [comment]
Added in ac7d709271982f87a0eb9fc460c3e1dbe228bf49.
Released in [v4.3.0](https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v4.3.0).

**Comment by hugop95** [comment]
For anyone looking to replicate the old `natural` sort, here is a sample config that will generate you the custom alphabet necessary:

```ts
import { Alphabet }  from 'eslint-plugin-perfectionist/alphabet'
import perfectionist from 'eslint-plugin-perfectionist'
import tseslint from 'typescript-eslint';
import naturalCompare from 'natural-compare-lite'; // You will have to install the package yourself

const alphabet = Alphabet
    .generateRecommendedAlphabet()
    .sortBy((a, b) => naturalCompare(a, b))
    .getCharacters();

export default [
    ...tseslint.config(tseslint.configs.recommended),
    {
        ...perfectionist.configs['recommended-custom'], // Use `custom` as a sort type
        settings: { // Set the `alphabet` option for all rules that you use for simplicity
            perfectionist: {
                alphabet: alphabet,
            },
        }
    }
]

```

**Comment by falkenhawk** [comment]
@hugop95 I like the new options and all the work done in #404 which brings in a nice alphabet builder etc. but perhaps you might consider specifying custom sorting function to be configured in plugin settings or per rule basis, when `type` is set to `custom`? 😅

**Comment by hugop95** [comment]
Hi @falkenhawk 

The alphabet builder exposes a 

- sortBy(sortingFunction: (characterA: string, characterB: string) => number): this

function that allows users to specify how to compare two characters.

Is this what you are looking for?

**Comment by falkenhawk** [comment]
not exactly, no - that method only sorts characters within the provided/generated alphabet - I meant a way to supply a totally custom sorting function, to be called with `(aValue, bValue)` just after https://github.com/azat-io/eslint-plugin-perfectionist/blob/main/utils/compare.ts#L123-L124, bypassing the use of the alphabet completely.

That would allow total customization of the sorting algorithm :)

**Comment by hugop95** [comment]
@falkenhawk 

> I meant a way to supply a totally custom sorting function

This is unfortunately not possible (at least not in a simple way): ESLint configs need to be [serializable](https://github.com/typescript-eslint/typescript-eslint/issues/9693#issuecomment-2261496829), so it's theoretically not possible to directly pass a function in the config.

In practice, it might be possible:
- By avoiding using ESLint features that depend on serialization (cache for example), it's probably possible to allow functions, but this is unstable and could break at any moment with changes from the ESLint team.
- By using `eval`: unsafe.
- By using `Function`: maybe there is something we can do here!

**Comment by hugop95** [comment]
@falkenhawk 

P.S: you should probably create a new issue for this, this will allow better tracking and improve the visibility of the request!
