### ISSUE TITLE
Bug: sort-enums negative values not sorted correctly with forceNumericSort: true

### ISSUE THREAD

**Issue by jeffphilp** [azat-io/eslint-plugin-perfectionist#386]
### Describe the bug

In the sort-enums rule when the forceNumericSort: true flag is set a negative value causes the ordering to fallback on the configured type (alphabetical etc.)

### Code example

```typescript
export enum NumericTypeCorrectOrder {
    One = 1,
    Two = 2,
    Three = 3
}

export enum NumericTypeWrongOrder {
    One = 1,
    OneNegative = -1, 
    Three = 3,
    Two = 2
}

```

### ESLint version

v9.15.0

### ESLint Plugin Perfectionist version

v4.0.3

### Additional comments

The sort-enums.ts source code has a check for determining an enum is a numeric one (https://github.com/azat-io/eslint-plugin-perfectionist/blob/main/rules/sort-enums.ts#L157)

```typescript
     let isNumericEnum = members.every(
        member =>
          member.initializer?.type === 'Literal' &&
          typeof member.initializer.value === 'number',
      )
```

I locally logged out the type for the members, and when it hit the negative value it had a type of `UnaryExpression` instead of `Literal`

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by hugop95** [comment]
@jeffphilp Thanks for the analysis! This will be fixed very soon.

**Comment by jeffphilp** [comment]
Thank you @hugop95 :)
