### ISSUE TITLE
Feature: sort-objects - add ignore rule for objects passed as arguments to function calls

### ISSUE THREAD

**Issue by SStranks** [azat-io/eslint-plugin-perfectionist#413]
### Describe the rule

There are times when passing objects directly to function calls that you would like the order of the objects to remain in a specific order e.g. with Redux slices, using the 'createSlice' function and passing in an object as first argument, following the documentation you would have 'name', 'initialState', 'reducers', etc, as the keys - there is an inherent logic/hierarchy to the ordering. 

You could add custom groupings for objects in the configuration, however this might conflict in different scenarios; you might not want the 'name' key to be first in one instance, but first in another. One could also use the ignore rule comment for the line in question, or the entire file, but then this introduces a lot of clutter to the files and you might not want to lose the rule for the entire file.

I would propose that there would be an option to specify an array of names of calling functions, to be excluded from the sort-objects rule e.g. 'createSlice'. Perhaps even linking it to the imported package it came from, e.g. '@reduxjs/toolkit/createSlice'.

### Code example

Without the sort-objects rule applied, you would have this arrangement as per the Redux documentation (as an example).

`export const authSlice = createSlice({
  name: 'auth',
  initialState,
  reducers: {
    setUser(state, action) {
      state.user = action.payload;
    }}`

You can't target the object from the configuration as the object is not named - naming the object first and passing it in introduces more clutter to the file, just to avoid the ordering issue.

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by hugop95** [comment]
This seems like a good fit for expanding the multi-configuration handling feature:

````
{
  useConfigurationIf: {
    callingFunctionPattern: "^createSlice$"
  },
  type: "unsorted"
}
````

**Comment by azat-io** [comment]
Added in 41c9f4f65cdea3fa13348ba19c66c9713584566e.
Released in [v4.4.0](https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v4.4.0).

**Comment by SStranks** [comment]
This enhancement doesn't seem to work when the function calls are being assigned to a variable;

Works: 
`createSlice({
  name: 'auth',
  initialState: 'a',
  reducers: {
    b: 'reducer'
  }
});`
`export default createSlice({
  name: 'auth',
  initialState: 'a',
  reducers: {
    b: 'reducer'
  }
});`

Does not work:
`const auth = createSlice({
  name: 'auth',
  initialState: 'a',
  reducers: {
    b: 'reducer'
  }
});`

**Comment by hugop95** [comment]
I see the issue, I'll work on a fix.
