### ISSUE TITLE
Bug: add `side-effect` import group to docs

### ISSUE THREAD

**Issue by ai** [azat-io/eslint-plugin-perfectionist#47]
### Describe the bug

[`sort-imports` docs](https://eslint-plugin-perfectionist.azat.io/rules/sort-imports) doesn’t have anything about [`side-effect` group](https://github.com/azat-io/eslint-plugin-perfectionist/issues/4)

### Code example

N/A

### ESLint version

N/A

### ESLint Plugin Perfectionist version

v1.5.0

### Validations

- [X] Read the [docs](https://eslint-plugin-perfectionist.azat.io).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
There is example of side-effect import.

What information do you think is missing?

**Comment by ai** [comment]
Hm, I didn't find group in https://eslint-plugin-perfectionist.azat.io/rules/sort-imports#groups because groups was not sorted like it was in default options (I expected it and look for `built-in` in the top of the list).

**Comment by azat-io** [comment]
The `builtin` group seems to be at the top of the list in the documentation at the moment.
