### ISSUE TITLE
Feature: builtin-type

### ISSUE THREAD

**Issue by dylang** [azat-io/eslint-plugin-perfectionist#5]
### What rule do you want to change?

sort-imports

## Config

```ts
groups: [
    ['builtin'],
    ['external', 'type'],
    ['internal', 'internal-type'],
    ['parent', 'parent-type'],
    ['sibling', 'sibling-type'],
    ['index', 'index-type'],
    'object',
    'unknown'
],
```

## Current

`http` is `builtin`.

```ts
import path from 'path';
import express, { static as serveStatic } from 'express';
import type { Server } from 'http'; // Yikes! This is a built in like path!
```

## Expected

```ts
import path from 'path';
import type { Server } from 'http'; // Much better!
import express, { static as serveStatic } from 'express';

```

### Code example

I'm not sure what change is required.

https://github.com/azat-io/eslint-plugin-perfectionist/blob/main/rules/sort-imports.ts

### Additional comments

Ideally we'd have something like this:

```ts
groups: [
    ['builtin', 'builtin-type'], // <--- I'm suggesting we add builtin-type.
    ['external', 'type'], // <--- Maybe type should be external-type?
    ['internal', 'internal-type'],
    ['parent', 'parent-type'],
    ['sibling', 'sibling-type'],
    ['index', 'index-type'],
    'object',
    'unknown'
],
```

### Validations

- [X] Read the [docs](https://eslint-plugin-perfectionist.azat.io).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Added in ca34b5ee78daf8a9dde88601cf6a4e0f203a7451

Released in [v1.1.0](https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v1.1.0)
