### ISSUE TITLE
Bug: (sort-imports) If there are comments above the import statement, automatic fixing will disrupt the layout.

### ISSUE THREAD

**Issue by 13OnTheCode** [azat-io/eslint-plugin-perfectionist#50]
### Describe the bug

If there are comments above the import statement, automatic fixing will disrupt the layout.

### Code example

eslint.config.js:

```js
import ESlintPluginPerfectionist from 'eslint-plugin-perfectionist'

export default [
  {
    files: ['**/*.js', '**/*.cjs', '**/*.mjs', '**/*.jsx'],
    ignores: ['**/*.min.*', '**/dist/**', '**/build/**', '**/node_modules/**', '**/.*/**'],
    languageOptions: {
      parserOptions: {
        ecmaFeatures: {
          jsx: true
        },
        ecmaVersion: 'latest',
        sourceType: 'module'
      }
    },
    plugins: {
      'perfectionist': ESlintPluginPerfectionist
    },
    rules: {
      ...ESlintPluginPerfectionist.configs['recommended-natural'].rules
    },
  }
]
```

index.js:
```js
// test
// test
import b from 'b.js'
import a from 'a.js'
```

result:
```js
// test
import a from 'a.js'
// test
import b from 'b.js'
```

expected result:
```js
// test
// test
import a from 'a.js'
import b from 'b.js'
```

### ESLint version

v8.45.0

### ESLint Plugin Perfectionist version

v1.5.1

### Validations

- [X] Read the [docs](https://eslint-plugin-perfectionist.azat.io).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
This is done intentionally so that comments on the code are preserved.

Input:

```js
// my module b
import b from 'b.js'
// my module a
import a from 'a.js'
```

Output:

```js
// my module a
import a from 'a.js'
// my module b
import b from 'b.js'
```

Do you have any idea how I can figure out if this is an import comment or a comment that doesn't apply to it?

**Comment by 13OnTheCode** [comment]
@azat-io Thank you for your explanation. It seems there isn't a definitive way to distinguish them, although it can be done by using single-line comments or multi-line comments. However, everyone has different writing habits.
