### ISSUE TITLE
Feature: allow to disable perfectionist for some objects

### ISSUE THREAD

**Issue by charnould** [azat-io/eslint-plugin-perfectionist#51]
### Describe the rule

First,`perfectionist` makes your code cleaner! Thanks.

**Context**

- I'm using `zod` to validate my form and some schema are quite long
- `perfectionist` throws me a lot of errors because my schema isn't well sorted
- However, I do not want my schema to be sorted. For example, I want:
   -  `longitude` to stay close to `latitude`
   - `support_email` close to `support_phone`
   - `author` close to `title`...

### Code example

What about having like `eslint` the ability to disable `perfectionist` for some files or objects like this: `// eslint-disable-perfectionist-next-line`

I've found nothing in Docs.

### Validations

- [X] Read the [docs](https://eslint-plugin-perfectionist.azat.io).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by charnould** [comment]
Didn't find anything in the Docs, but VSCode has just (?) shown me: `/* eslint-disable perfectionist/sort-objects */
`

**Comment by nitreojs** [comment]
sooo any ideas to implement this as an option? for example, an ability to disable sorting for sort-classes and such, but still have sort-classes to follow the `groups` part of a setting

**Comment by azat-io** [comment]
@nitreojs Is it works for you? https://eslint-plugin-perfectionist.azat.io/rules/sort-objects#ignore-pattern
