### ISSUE TITLE
Feature: sort-objects - include objects as used as function parameters 

### ISSUE THREAD

**Issue by dylang** [azat-io/eslint-plugin-perfectionist#6]
### What rule do you want to change?

sort-objects

### Describe the problem

```ts
const foo = (
    // The parameters are currently not sorted.
    {
        y,
        x
    }: // But the types are sorted.
    // So the params and types aren't in the same order anymore.
    { 
        x: number; 
        y: number 
    }
) => ({ x, y });

```

### Code example

I'm guessing in https://github.com/azat-io/eslint-plugin-perfectionist/blob/main/rules/sort-objects.ts but I don't know the AST.

### Validations

- [X] Read the [docs](https://eslint-plugin-perfectionist.azat.io).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Fixed in 65fe6c74a5b63d307e0fa577566f4d9f540f4028

Released in [v1.1.0](https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v1.1.0)
