### ISSUE TITLE
Bug: does not sort in-line typings

### ISSUE THREAD

**Issue by askew07** [azat-io/eslint-plugin-perfectionist#64]
### Describe the bug

When sorting objects, seems like in-line TypeScript parameter types are not being sorted as expected.

### Code example

This

<img width="366" alt="image" src="https://github.com/azat-io/eslint-plugin-perfectionist/assets/95476521/2806d3ee-9f57-4414-9870-788bcb1bb1bd">

Becomes this:

<img width="372" alt="image" src="https://github.com/azat-io/eslint-plugin-perfectionist/assets/95476521/053e9c47-dc81-4060-ab4e-3b5d3642a19e">

The arguments are sorted, but the in-line types are not.

### ESLint version

v8.45.0

### ESLint Plugin Perfectionist version

v.2.0.0

### Validations

- [X] Read the [docs](https://eslint-plugin-perfectionist.azat.io).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
I'm having trouble reproducing the problem. Could you show me your ESLint config?
Are you using `sort-object-types` rule?

**Comment by askew07** [comment]
@azat-io Apologies for the delay. I tried this once more with latest of your plugin (`2.1.0`) and... I am no longer reproducing the issue. Now sure when this was fixed, but I could easily replicate the issue in previous versions.

Anyway, closing this, as this is no longer an issue. Thanks!
