### ISSUE TITLE
Feature: sort-exports

### ISSUE THREAD

**Issue by dylang** [azat-io/eslint-plugin-perfectionist#7]
### Describe the rule

Helpful for barrel files (index.ts).

### Not sorted

```ts
export { readPackageJson } from './read-package-json';
export { loadDotEnv } from './load-dot-env';
export { getGitBranch } from './get-git-branch';
```

### Sorted natural asc

```ts
export { getGitBranch } from './get-git-branch';
export { loadDotEnv } from './load-dot-env';
export { readPackageJson } from './read-package-json';
```

### Additional comments

I'm not sure if we need the same `groups` support as `sort-imports`. 

Changing export order could have side effects if the same name is exported multiple times.

```ts
export * from './util';
export * from './abc';
```

If they both export something with the same name then changing the order could change which one is exported. Exporting with the same name is a bad practice, so this might help find those bugs.

### Validations

- [X] Read the [docs](https://eslint-plugin-perfectionist.azat.io).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Good idea, thank you. This rule should definitely be in the plugin

**Comment by azat-io** [comment]
Added in a71eeb3c6d059c3c4cc82c280e871dee0b6c3df9

Will be released today

**Comment by azat-io** [comment]
Releases in [v1.2.0](https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v1.2.0)
