### ISSUE TITLE
Feature: Consistent the order same line-length entities

### ISSUE THREAD

**Issue by nam-hle** [azat-io/eslint-plugin-perfectionist#71]
### What rule do you want to change?

sort-named-imports,sort-jsx-props 

### Describe the problem

Be enabling line-length for sort-name-imports/sort-jsx-props (and others), the same length entities can be re-order after some code manipulations.

### Code example

E.g: I have
`import { all, put, call, select } from "typed-redux-saga";`

After remove the statement containg `all` and `put` functions, then revert the deletion, then re-import in order `put` then `all`. So the import statement becomes:
`import { put, all, call, select } from "typed-redux-saga";`
which is a unnecessary change.

### Additional comments

Plugin version v2.1.0

### Validations

- [X] Read the [docs](https://eslint-plugin-perfectionist.azat.io).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
I am currently unable to reproduce your problem. Can you tell me how I can do this?
