### ISSUE TITLE
Feature: (Sort exports by path)

### ISSUE THREAD

**Issue by andris2233** [azat-io/eslint-plugin-perfectionist#74]
### Describe the rule

Sort "export * from '...'" structures by path

### Code example

I have the following index file:
``` ts
export * from "./useSomething2";
export * from "./useSomething3";
export * from "./useSomething1";
```
I want to be able to change the export order along the path:
``` ts
export * from "./useSomething1";
export * from "./useSomething2";
export * from "./useSomething3";
```

### Validations

- [X] Read the [docs](https://eslint-plugin-perfectionist.azat.io).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Sorry, we do not sort exports with `*` for security reasons. Such exports may contain modules with the same names, which can lead to conflicts and problems. I recommend doing this manually.
