### ISSUE TITLE
Feature: group "state" and "behaviour" members

### ISSUE THREAD

**Issue by askew07** [azat-io/eslint-plugin-perfectionist#76]
### What rule do you want to change?

sort-interfaces AND sort-object-types

### Describe the problem

@azat-io 
When sorting interface or types, the current rules sort alphabetically; but the end result does not read right (IMO). Let me explain:

We can say that the type definition of an object (an `interface` or `type`) holds two kinds of distinct members:

1. Members that define the _state_ of the object: properties / fields / "keys". NOTE: by _state_ I mean properties/fields that hold values that _could_  mutate, and alter the "state" of an object.
2. Members that define _behaviour_ of the object: methods / functions and such.

Knowing above, I think that when sorting an `interface` or a `type`, it reads _much_ better if we could group by these two different member types: properties/fields/'keys' vs methods/functions, etc.

It just... reads better, IMO. As far as I know (and I tried), it is not possible in current `2.1.0` version to accomplish that.

### Code example

This is how `sort-interfaces` rule currently sort (alphabetical):

```ts
export interface IUserRepository {
  connectionString: string
  getConnectionString: () => Promise<string>
  getFullUserName: (userId: string) => Promise<string>
  host: string
  revealSecret: () => Promise<string>
  secretPath: string
  setTimeOut: (value: string) => void
  userName: string
}
```

Proposed outcome:

```ts
export interface IUserRepository {
  connectionString: string
  host: string
  secretPath: string
  userName: string
  getConnectionString: () => Promise<string>
  getFullUserName: (userId: string) => Promise<string>
  revealSecret: () => Promise<string>
  setTimeOut: (value: string) => void
}
```

### Additional comments

When sorting interfaces or types (and probably objects as well), it would be cool if the rules could automatically group `state` members vs `behaviour`  members, and sort these groups individually.

(Keep in mind that I am adding comments in the interface to clarify, but the rule should not add comments)

Example:

```ts
export interface IUserRepository {
  // below: members that define "state" are grouped first,
  // then sorted.
  connectionString: string
  host: string
  secretPath: string
  userName: string
  // below: members that define "behaviour" are grouped next,
  // then sorted.
  getConnectionString: () => Promise<string>
  getFullUserName: (userId: string) => Promise<string>
  revealSecret: () => Promise<string>
  setTimeOut: (value: string) => void
}
```

Specially (but not exclusively) in large interfaces or types, above reads much better.

### Validations

- [X] Read the [docs](https://eslint-plugin-perfectionist.azat.io).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by askew07** [comment]
@azat-io Giving above a second thought, I think my proposal above should apply to everything, not just type definitions (`interface` / `type`):

- Object in general (A current use case we have in our monorepo, is large GraphQL objects with mixed state properties and functions that define behaviour)
- Classes
- etc.

**Comment by azat-io** [comment]
You can create your own groups like this:

```js
    "perfectionist/sort-interfaces": [
      "error",
      {
        groups: [
          "unknown",
          ["get-functions", "set-functions"],
        ],
        "custom-groups": {
          "get-functions": "get*",
          "set-functions": "set*",
        }
      }
    ]
```

Does this solution not work for you?

**Comment by askew07** [comment]
@azat-io Problem with above approach is that it matches by name (`get*`, `set*`, `update*`, and so), but many people work on really big monorepos with tons packages/services and tracking down the name of each function to try to match it like above ^, becomes an impossible task (and it's not maintainable in the long term)

Because of that, my suggestion above was _not_ to match by name (`get*`), but to offer the option to match by type. Example: `function` (any kind of function). So, if inside `groups` I am able to specify `function` as item type, any kind of function (independently of its name) will be matched and sorted the way we wish.

In my personal preferences (as described above), functions/methods should be sorted at the very bottom, after everything.

**Comment by azat-io** [comment]
We have decided to leave the current implementation of the rule work.
