### ISSUE TITLE
Bug: how to configure perfectionist to work with script blocks in .svelte files

### ISSUE THREAD

**Issue by opensas** [azat-io/eslint-plugin-perfectionist#77]
### Describe the bug

I follow these steps to create a SvelteKit project and configure it to work with perfectionist:

```shell
$ pnpm create svelte@latest perfectionist-test

◇  Which Svelte app template?
│  Skeleton project
│
◇  Add type checking with TypeScript?
│  Yes, using TypeScript syntax
│
◆  Select additional options (use arrow keys/space bar)
│  ◼ Add ESLint for code linting

$ cd perfectionist-test/

$ pnpm install

$ pnpm add --save-dev eslint-plugin-perfectionist
```

update default `.eslintrc.cjs` file

```
module.exports = {
  root: true,
  extends: [
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:svelte/recommended",
  ],
  parser: "@typescript-eslint/parser",
  plugins: ["@typescript-eslint", "perfectionist"],
  rules: {
    "perfectionist/sort-array-includes": [
      "error",
      {
        type: "natural",
        order: "asc",
        "spread-last": true,
      },
    ],
  },
  parserOptions: {
    sourceType: "module",
    ecmaVersion: 2020,
    extraFileExtensions: [".svelte"],
  },
  env: {
    browser: true,
    es2017: true,
    node: true,
  },
  overrides: [
    {
      files: ["*.svelte"],
      parser: "svelte-eslint-parser",
      // Parse the `<script>` in `.svelte` as TypeScript
      parserOptions: {
        parser: "@typescript-eslint/parser",
      },
    },
  ],
};
```

Add the following to `src/lib/index.ts` file

```typescript
// place files you want to import through the `$lib` alias in this folder.

export function isAllowed(role: string) {
	return [
		'maintainer',
		'admin',
		'developer',
		'owner',
		'observer'
		].includes(role)
}
```

add the following `src/lib/component/Component.svelte` file

```svelte
<script type="ts">
	const ROLES = [
		'maintainer',
		'admin',
		'developer',
		'owner',
		'observer'
	]
	$: console.log({ROLES});
</script>
```

The index.ts file is correctly processed by eslint, but the svelte file is not

![image](https://github.com/azat-io/eslint-plugin-perfectionist/assets/481687/be9166b4-6e8a-4bdd-880e-98b319df3437)

and running `eslint . --fix` fixes the ts file, but not the svelte one

```typescript
export function isAllowed(role: string) {
	return [
		'admin',
		'developer',
		'maintainer',
		'observer',
		'owner'
		].includes(role)
}
``` 

note: added this repo with the configured project: https://github.com/opensas/periodic-test

you can open it with [gitpod](https://gitpod.io/#https://github.com/opensas/periodic-test) [here](https://gitpod.io/#https://github.com/opensas/periodic-test)

### Code example

Component.svelte file

```svelte
<script type="ts">
	const ROLES = [
		'maintainer',
		'admin',
		'developer',
		'owner',
		'observer'
	]
	$: console.log({ROLES});
</script>
```

### ESLint version

"eslint": "^8.28.0"

### ESLint Plugin Perfectionist version

"eslint-plugin-perfectionist": "^2.1.0"

### Additional comments

		"@typescript-eslint/eslint-plugin": "^6.0.0",
		"@typescript-eslint/parser": "^6.0.0",
		"eslint": "^8.28.0",
		"eslint-plugin-perfectionist": "^2.1.0",
		"eslint-plugin-svelte": "^2.30.0",

### Validations

- [X] Read the [docs](https://eslint-plugin-perfectionist.azat.io).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
We can't sort arrays because it might affect how the program works.

We sort arrays only if the `includes` method is called immediately after creating them.
