### ISSUE TITLE
Bug: Allow for sorting on certain groups and not others

### ISSUE THREAD

**Issue by JacksonUtsch** [azat-io/eslint-plugin-perfectionist#79]
### Describe the bug

I can't seem to sort class properties without also including class methods. Using nestjs some of my methods need to be sorted a certain way and changing breaks the API.

### Code example

```js
"perfectionist/sort-classes": [
    "error",
    {
        "type": "natural",
        "order": "asc",
        "groups": [
          "property",
        ]
    }
],   
```

### ESLint version

8.44.0

### ESLint Plugin Perfectionist version

2.1.0

### Validations

- [X] Read the [docs](https://eslint-plugin-perfectionist.azat.io).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Could you show me example?
What do you have now, what do you want to have, and what are the problems?

**Comment by azat-io** [comment]
The issue was closed due to inactivity.
