### ISSUE TITLE
Bug: perfectionist/sort-interfaces - don't sort new

### ISSUE THREAD

**Issue by dylang** [azat-io/eslint-plugin-perfectionist#8]
### Describe the bug

If an interface describes a class, I think `new` has to be stay first.

### Before

```ts
export interface ClassExample<T> {
    new (...args: unknown[]): T; // <-- good
    (...args: unknown[]): Partial<T>;
}
```

### After

```ts
export interface ClassExample<T> {
    (...args: unknown[]): Partial<T>;
    new (...args: unknown[]): T; // <-- bad
}
```

### ESLint version

v8.41.0

### ESLint Plugin Perfectionist version

v1.1.0

### Validations

- [X] Read the [docs](https://eslint-plugin-perfectionist.azat.io).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Perhaps there should be an option for this, like the `callback`, `multiline` and `shorthand` options in the [sort-jsx-props](https://eslint-plugin-perfectionist.azat.io/rules/sort-jsx-props#callback) rule?

Or do you think it should be standard behavior?

Because the current implementation seems predictable to me.

**Comment by dylang** [comment]
I'm not sure, I believe the order change of `new` made the typescript compiler unhappy.

**Comment by azat-io** [comment]
Can you show me full code example?
I don't understand the difference at this time.

**Comment by azat-io** [comment]
```ts
interface A {
  new (): number;
  (): string;
}
declare const A: A;
let x = new A();
//  ^? - let x: number
let y = A();
//  ^? - let y: string

interface B {
  (): string;
  new (): number;
}
declare const B: B;
let z = new B();
//  ^? - let z: number
let w = B();
//  ^? - let w: string
```

I have no luck reproducing the problem.

Looks like `new` overloads and `regular` overloads are completely separate.
