### ISSUE TITLE
Feature: Add a sort-intersection-types rule?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [azat-io/eslint-plugin-perfectionist#84]
### Describe the rule

https://eslint-plugin-perfectionist.azat.io/rules/sort-union-types exists for _union_ types, but what about _intersection_ types?

### Code example

```ts
// ❌ Incorrect
type Both =
  & { b: 1 }
  & { a: 1 }

// ✅ Correct
type Both =
  & { a: 1 }
  & { b: 1 }
```

### Additional comments

We intentionally named https://typescript-eslint.io/rules/sort-type-constituents as _"type constituents"_ because that refers to the constituents in both intersection and union types. Fun fact!

### Validations

- [X] Read the [docs](https://eslint-plugin-perfectionist.azat.io).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Nice idea! I'll add it. ❤️️️
