### ISSUE TITLE
Feature: add `side-effect-style`

### ISSUE THREAD

**Issue by ai** [azat-io/eslint-plugin-perfectionist#88]
### What rule do you want to change?

sort-imports

### Describe the problem

In recent changes `import "a.css"` moved to `side-effect` group, but previously it was in `style` group.

The changes have own logic.

But what if we will add extra `side-effect-style` group for imports like `import "a.css"` to be able to customize them?

### Code example

```js
import './colors.css'
import './environment.js'
import './index.css'
import './reset.css'

import { getPagePath } from '@nanostores/router'
import { isGuestRoute, isSlowRoute, router, theme } from '@slowreader/core'

import { urlRouter } from '../stores/router.js'
import Main from './main.svelte'
```

### Validations

- [X] Read the [docs](https://eslint-plugin-perfectionist.azat.io).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Good idea.

Added in 32dbef88a41dfc8f8478ee0ec31eb1632cd7e97a.
Released in [v2.4.0](https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v2.4.0)
