### ISSUE TITLE
Bug: sort-imports auto-fixing

### ISSUE THREAD

**Issue by pont1s** [azat-io/eslint-plugin-perfectionist#89]
### Describe the bug

Hello!

I'm having a problem with auto-fixing import sorting (src/pages/CartAutoFixIssue.vue). I noticed that this problem occurs when more than 6 `custom-groups` are specified in the `group` parameter. At the same time, finding the error works correctly, this can be checked by correcting the file manually (src/pages/CartTestAnalysis.vue)

Thanks!

### Code example

Reproduction repository: https://github.com/pont1s/eslint-plugin-perfectionist-import-issue

### ESLint version

8.54.0

### ESLint Plugin Perfectionist version

2.4.0

### Validations

- [X] Read the [docs](https://eslint-plugin-perfectionist.azat.io).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Fixed in 6847eaff0afa2c2c3094cb55fc3a0e8b5f9c7844.
Released in [v2.4.1](https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v2.4.1).

Thank you for the issue!
