### ISSUE TITLE
Allow custom sorting for sort-array-includes

### ISSUE THREAD

**Issue by DB-Alex** [azat-io/eslint-plugin-perfectionist#98]
### What rule do you want to change?

sort-array-includes

### Describe the problem

Would be great to have the same logic als sort-objects in array-includes.

### Code example

Current behaviour:

['lg', 'md', 'xl'].includes(breakpoint)

Would be great if it could be:

['md', 'lg', ', 'xl'].includes(breakpoint)

### Validations

- [X] Read the [docs](https://eslint-plugin-perfectionist.azat.io).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Added in a06ce5c96f55e8eb64e808e14972766befa3c8ad.
Released in [v4.4.0](https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v4.4.0).
