### ISSUE TITLE
use auto fix without any warnings or errors 

### ISSUE THREAD

**Issue by issam-seghir** [azat-io/eslint-plugin-perfectionist#99]
### Describe the bug

Can the auto-fix (sort) feature be enabled when I hit Ctrl+S, but disable the warning messages? Currently, when I disable the warning messages like this: 

rules: {
    "perfectionist/sort-object-types": "off",
}

it also disables the auto-fix feature. In summary, I want the code to be sorted automatically when I hit save, without any errors or warning messages because they are not necessary.

![image](https://github.com/azat-io/eslint-plugin-perfectionist/assets/74573675/e6850a49-5b22-4f3f-bd61-1d7b17b46a3d)

### Code example

...

### ESLint version

8.55.0

### ESLint Plugin Perfectionist version

2.5.0

### Validations

- [X] Read the [docs](https://eslint-plugin-perfectionist.azat.io).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
This seems to be a limitation of ESLint, you can only use autofix if you have an error. Have you seen something similar in other ESLint rules?

**Comment by issam-seghir** [comment]
> have you seen something similar in other ESLint rules?
Unfortunately  no, i used to change "error" to "warning" for plugins such as `sort-import`  ,  but this plugin is annoying because it throws errors in every place

**Comment by azat-io** [comment]
Unfortunately, there doesn't seem to be anything I can do to help here. This is the ESLint API.
